#!/usr/bin/env python3
"""Generate a deterministic SQL seed for the Crew Scheduling section.

Emits INSERTs for a realistic Wilmington, NC operation into the sched_* tables
(seed org 00000000-0000-0000-0000-000000000001). Deterministic UUIDs (uuid5) so
re-running produces the same ids; the file DELETEs the seed org first so it is
safe to paste repeatedly.

    python3 backend/scripts/gen_scheduling_seed.py > supabase/seed/scheduling_seed.sql
"""
from __future__ import annotations

import random
import sys
import uuid
from datetime import date, datetime, timedelta

ORG = "00000000-0000-0000-0000-000000000001"
NS = uuid.UUID("11111111-2222-3333-4444-555555555555")
random.seed(42)

# The board's first visible week — Monday anchoring "today" (~2026-08-03).
WEEK1 = date(2026, 8, 3)
# Optional CLI overrides for a compact, chat-pasteable seed: gen ... <weeks> <njobs>
WEEKS = int(sys.argv[1]) if len(sys.argv) > 1 else 6
_N_OVERRIDE = int(sys.argv[2]) if len(sys.argv) > 2 else None

out: list[str] = []
def emit(s: str = "") -> None: out.append(s)
def uid(kind: str, key) -> str: return str(uuid.uuid5(NS, f"{kind}:{key}"))
def q(s) -> str:
    if s is None: return "null"
    return "'" + str(s).replace("'", "''") + "'"
def n(x) -> str: return "null" if x is None else str(x)
def ts(dt: datetime) -> str: return "'" + dt.strftime("%Y-%m-%d %H:%M:%S") + "'"
def d(dd: date) -> str: return "'" + dd.isoformat() + "'"

emit("-- Generated by backend/scripts/gen_scheduling_seed.py — do not edit by hand.")
emit("-- Realistic Wilmington, NC operation for the Crew Scheduling section.")
emit(f"-- Seed org {ORG}. Safe to paste repeatedly (clears the seed org first).")
emit("begin;")

# Clear seed org (child -> parent).
for t in ["sched_assignment", "sched_appointment", "sched_job_tag_link", "sched_job",
          "sched_non_job_event", "sched_shift", "sched_crew_skill", "sched_crew_membership",
          "sched_crew", "sched_person", "sched_business_unit", "sched_customer",
          "sched_property", "sched_job_tag", "sched_audit_event"]:
    emit(f"delete from {t} where org_id = '{ORG}';")
emit("delete from sched_weather_day where postal_prefix in ('284','285');")
emit()

# ---------- Business units ----------
BUS = [
    ("Roofing Service", "bu-service", 0),
    ("Roofing Install", "bu-install", 1),
    ("Gutters",         "bu-gutter",  2),
    ("Siding",          "bu-siding",  3),
]
emit("insert into sched_business_unit (id, org_id, name, color_token, sort_order) values")
rows = [f"  ({q(uid('bu', name))}, '{ORG}', {q(name)}, {q(ct)}, {so})" for name, ct, so in BUS]
emit(",\n".join(rows) + ";\n")
BU = {name: uid("bu", name) for name, _, _ in BUS}

# ---------- People (22) ----------
FIRST = ["Kevin","Marcus","Travis","Diego","Cody","Brett","Luis","Shane","Devin","Tyrone",
         "Jared","Colton","Mateo","Wesley","Grant","Hector","Blake","Isaiah","Dustin","Reid","Owen","Caleb"]
LAST = ["Barnes","Whitfield","Nguyen","Alvarez","Pope","Hutchins","Ramos","McKay","Coleman","Bell",
        "Sutton","Fry","Delgado","Cross","Boone","Vega","Simms","Ford","Poe","Hardy","Nixon","Reece"]
ROLES = (["FOREMAN"] * 6) + (["INSTALLER"] * 11) + (["APPRENTICE"] * 4) + (["SUBCONTRACTOR"] * 1)
people = []
emit("insert into sched_person (id, org_id, first_name, last_name, phone, role) values")
prows = []
for i in range(22):
    pid = uid("person", i)
    people.append((pid, ROLES[i]))
    phone = f"910-555-{1000 + i:04d}"
    prows.append(f"  ({q(pid)}, '{ORG}', {q(FIRST[i])}, {q(LAST[i])}, {q(phone)}, {q(ROLES[i])})")
emit(",\n".join(prows) + ";\n")
foremen = [p for p, r in people if r == "FOREMAN"]

# ---------- Crews (7) ----------
# name, business_unit, squares/day, tearoff/day, maxPitch, maxStories, skills
CREWS = [
    ("Kevin's Crew",    "Roofing Install", 28, 16, 9.0, 2, ["ASPHALT_SHINGLE"]),
    ("Install Team 2",  "Roofing Install", 24, 14, 9.0, 2, ["ASPHALT_SHINGLE", "METAL"]),
    ("Summit Steep",    "Roofing Install", 20, 12, 12.0, 3, ["ASPHALT_SHINGLE", "STEEP_SLOPE"]),
    ("Metro Install",   "Roofing Install", 34, 18, 9.0, 2, ["ASPHALT_SHINGLE"]),
    ("Service & Repair","Roofing Service", 18, 10, 9.0, 2, ["ASPHALT_SHINGLE", "GUTTER"]),
    ("Gutter Crew",     "Gutters",         30, 6,  9.0, 2, ["GUTTER"]),
    ("Siding Squad",    "Siding",          22, 12, 9.0, 2, ["SIDING"]),
]
crew_ids = []
emit("insert into sched_crew (id, org_id, name, business_unit_id, lead_id, is_active, squares_per_day, tear_off_squares_per_day, max_pitch, max_stories) values")
crows = []
for i, (name, bu, spd, tspd, mp, ms, _sk) in enumerate(CREWS):
    cid = uid("crew", name); crew_ids.append((cid, name, bu, spd, mp, _sk))
    lead = foremen[i % len(foremen)]
    crows.append(f"  ({q(cid)}, '{ORG}', {q(name)}, {q(BU[bu])}, {q(lead)}, true, {spd}, {tspd}, {mp}, {ms})")
emit(",\n".join(crows) + ";\n")

# ---------- Skills ----------
emit("insert into sched_crew_skill (id, org_id, crew_id, skill) values")
srows = []
for cid, name, _bu, _spd, _mp, sk in crew_ids:
    for s in sk:
        srows.append(f"  ({q(uid('skill', cid + s))}, '{ORG}', {q(cid)}, {q(s)})")
emit(",\n".join(srows) + ";\n")

# ---------- Memberships (distribute people; one floating) ----------
emit("insert into sched_crew_membership (id, org_id, crew_id, person_id, is_floating) values")
mrows = []
non_foremen = [p for p, r in people if r != "FOREMAN"]
for idx, (pid, role) in enumerate(people):
    cid = crew_ids[idx % len(crew_ids)][0]
    floating = (idx == 5)  # one floating member, borrowable
    mrows.append(f"  ({q(uid('mem', pid))}, '{ORG}', {q(cid)}, {q(pid)}, {str(floating).lower()})")
emit(",\n".join(mrows) + ";\n")

# ---------- Shifts (6 weeks Mon-Fri; Sat for 2 crews) + PTO event ----------
emit("insert into sched_shift (id, org_id, crew_id, date, start_time, end_time, type) values")
shrows = []
sat_crews = {crew_ids[0][0], crew_ids[3][0]}  # Kevin's + Metro on Saturdays
for w in range(WEEKS):
    monday = WEEK1 + timedelta(days=7 * w)
    for cid, *_ in crew_ids:
        for dow in range(5):  # Mon-Fri
            day = monday + timedelta(days=dow)
            shrows.append(f"  ({q(uid('shift', cid + str(day)))}, '{ORG}', {q(cid)}, {d(day)}, '07:00', '17:00', 'REGULAR')")
        if cid in sat_crews:
            sat = monday + timedelta(days=5)
            shrows.append(f"  ({q(uid('shift', cid + str(sat)))}, '{ORG}', {q(cid)}, {d(sat)}, '07:00', '15:00', 'OVERTIME')")
emit(",\n".join(shrows) + ";\n")

# Service & Repair PTO: 3 days mid-week 1 (Wed-Fri).
sr_crew = crew_ids[4][0]
emit("insert into sched_non_job_event (id, org_id, crew_id, title, start_at, end_at, blocks_capacity) values")
pto_start = datetime.combine(WEEK1 + timedelta(days=2), datetime.min.time()).replace(hour=0)
pto_end = datetime.combine(WEEK1 + timedelta(days=4), datetime.min.time()).replace(hour=23, minute=59)
emit(f"  ({q(uid('pto', sr_crew))}, '{ORG}', {q(sr_crew)}, 'PTO — foreman out', {ts(pto_start)}, {ts(pto_end)}, true);\n")

# ---------- Tags ----------
TAGS = [("Insurance","tag-info","INFO"),("Waive Trip","tag-warn","WARN"),
        ("Callback","tag-crit","CRITICAL"),("Warranty","tag-info","INFO"),("HOA approval","tag-warn","WARN")]
emit("insert into sched_job_tag (id, org_id, label, color_token, severity) values")
emit(",\n".join(f"  ({q(uid('tag', lbl))}, '{ORG}', {q(lbl)}, {q(ct)}, {q(sev)})" for lbl, ct, sev in TAGS) + ";\n")
TAGID = {lbl: uid("tag", lbl) for lbl, _, _ in TAGS}

# ---------- Customers + Properties + Jobs (~90) ----------
STREETS = ["Market St","Oleander Dr","Wrightsville Ave","College Rd","Carolina Beach Rd","Eastwood Rd",
           "Military Cutoff Rd","Shipyard Blvd","Castle Hayne Rd","Gordon Rd","Piner Rd","Masonboro Loop Rd",
           "Village Rd","Ocean Hwy","Fayetteville Rd","Lanvale Rd","Old Fayetteville Rd","Howe St",
           "Long Beach Rd","Yaupon Dr","Country Club Rd","Snows Cut","Dow Rd","Live Oak Dr","Middle Sound Loop Rd",
           "Porters Neck Rd","Sidbury Rd","Blue Clay Rd","Holly Shelter Rd","River Rd"]
PLACES = [("Wilmington","NC","28403",34.212,-77.887),("Wilmington","NC","28405",34.246,-77.870),
          ("Wilmington","NC","28409",34.155,-77.884),("Leland","NC","28451",34.226,-78.044),
          ("Southport","NC","28461",33.921,-78.020),("Carolina Beach","NC","28428",34.035,-77.893),
          ("Hampstead","NC","28443",34.367,-77.710),("Castle Hayne","NC","28429",34.352,-77.900)]
JOB_TYPES_BY_BU = {
    "Roofing Install": ["REROOF","NEW_ROOF_INSTALL"],
    "Roofing Service": ["ROOF_REPAIR","INSPECTION"],
    "Gutters": ["GUTTER_REPAIR","GUTTER_INSTALL"],
    "Siding": ["SIDING_REPAIR","NEW_SIDING_INSTALL"],
}
STATUS_POOL = (["SOLD"] * 8 + ["SCHEDULED"] * 6 + ["IN_PROGRESS"] * 3 + ["ESTIMATE"] * 3
               + ["COMPLETE"] * 3 + ["ON_HOLD"] * 2 + ["CANCELED"] * 1)

cust_rows, prop_rows, job_rows, link_rows = [], [], [], []
jobs = []  # (jid, bu, job_type, status, squares, pitch, stories, planned crew days-ish)
N = _N_OVERRIDE or 90
for i in range(N):
    cid_ = uid("cust", i); pid_ = uid("prop", i); jid = uid("job", i)
    fn = random.choice(FIRST); ln = random.choice(LAST)
    cust_rows.append(f"  ({q(cid_)}, '{ORG}', {q(fn)}, {q(ln)}, {q(f'910-555-{2000+i:04d}')}, {q(fn.lower()+'.'+ln.lower()+'@example.com')})")
    city, st, zp, blat, blng = random.choice(PLACES)
    lat = round(blat + random.uniform(-0.03, 0.03), 6); lng = round(blng + random.uniform(-0.03, 0.03), 6)
    line1 = f"{random.randint(100, 8999)} {random.choice(STREETS)}"
    prop_rows.append(f"  ({q(pid_)}, '{ORG}', {q(line1)}, {q(city)}, {q(st)}, {q(zp)}, {lat}, {lng})")

    bu_name = random.choice(list(JOB_TYPES_BY_BU.keys()))
    jt = random.choice(JOB_TYPES_BY_BU[bu_name])
    status = STATUS_POOL[i % len(STATUS_POOL)]
    priority = random.choices(["ROUTINE", "HIGH", "URGENT"], weights=[80, 15, 5])[0]

    missing = i < max(2, N // 8)  # a slice deliberately missing measurements
    if missing:
        squares = pitch = stories = None; tear = 0; waste = None
    else:
        if jt in ("REROOF", "NEW_ROOF_INSTALL"):
            squares = round(random.uniform(22, 48), 1); tear = random.choice([0, 1, 1, 2])
        elif jt in ("ROOF_REPAIR",):
            squares = round(random.uniform(2, 6), 1); tear = random.choice([0, 1])
        elif jt in ("GUTTER_REPAIR", "GUTTER_INSTALL", "SIDING_REPAIR"):
            squares = round(random.uniform(3, 12), 1); tear = 0
        else:  # NEW_SIDING_INSTALL
            squares = round(random.uniform(14, 30), 1); tear = 0
        pitch = round(random.choice([4, 5, 6, 6, 7, 8, 8, 9, 10, 12]) + 0.0, 1)
        stories = random.choice([1, 1, 2, 2, 3])
        waste = round(random.choice([12, 13, 15]) + 0.0, 2)

    sold = round(squares * random.uniform(380, 620), 2) if squares else round(random.uniform(400, 3000), 2)
    deadline = d(WEEK1 + timedelta(days=random.randint(4, 20))) if priority != "ROUTINE" else "null"
    job_rows.append(
        f"  ({q(jid)}, '{ORG}', {q(BU[bu_name])}, {q(cid_)}, {q(pid_)}, {q(jt)}, {q(status)}, {q(priority)}, "
        f"{sold}, null, null, {n(squares)}, {n(pitch)}, {n(stories)}, {tear}, {n(waste)}, {deadline}, null)"
    )
    jobs.append((jid, bu_name, jt, status, squares, pitch, stories))
    # a few tags
    if random.random() < 0.35:
        link_rows.append(f"  ('{ORG}', {q(jid)}, {q(TAGID[random.choice(list(TAGID))])})")

emit("insert into sched_customer (id, org_id, first_name, last_name, phone, email) values")
emit(",\n".join(cust_rows) + ";\n")
emit("insert into sched_property (id, org_id, line1, city, state, postal_code, lat, lng) values")
emit(",\n".join(prop_rows) + ";\n")
emit("insert into sched_job (id, org_id, business_unit_id, customer_id, property_id, job_type, status, priority, "
     "sold_amount, estimated_cost, measurement_run_id, squares, predominant_pitch, stories, tear_off_layers, "
     "waste_factor_pct, deadline, notes) values")
emit(",\n".join(job_rows) + ";\n")
if link_rows:
    emit("insert into sched_job_tag_link (org_id, job_id, tag_id) values")
    # de-dup (job,tag)
    seen = set(); uniq = []
    for r in link_rows:
        if r not in seen: seen.add(r); uniq.append(r)
    emit(",\n".join(uniq) + " on conflict do nothing;\n")

# ---------- Appointments + Assignments ----------
# Schedule SCHEDULED + IN_PROGRESS jobs into week 1/2, deliberately overbooking
# Kevin's Crew, with 3 multi-day series (one mid-week for the series-break test).
appt_rows, asgn_rows = [], []
install_crews = [c for c in crew_ids if c[2] == "Roofing Install"]
schedulable = [j for j in jobs if j[3] in ("SCHEDULED", "IN_PROGRESS") and j[4]]

def add_appt(jid, crew_id, day, seq, total, planned, status):
    aid = uid("appt", f"{jid}:{seq}")
    start = datetime.combine(day, datetime.min.time()).replace(hour=7)
    end = start.replace(hour=15)
    appt_rows.append(f"  ({q(aid)}, '{ORG}', {q(jid)}, {seq}, {total}, {ts(start)}, {ts(end)}, {q(status)}, {n(planned)}, false)")
    asgn_rows.append(f"  ({q(uid('asgn', aid))}, '{ORG}', {q(aid)}, {q(crew_id)}, true)")

kevin = crew_ids[0][0]
# Overbook Kevin's Crew: pile several jobs onto Tue 08-04.
overbook_day = WEEK1 + timedelta(days=1)
for k, j in enumerate([x for x in schedulable if x[1] == "Roofing Install"][:4]):
    add_appt(j[0], kevin, overbook_day, 1, 1, j[4], "SCHEDULED")

# 3 multi-day series in progress (one mid-week).
series_jobs = [x for x in schedulable if x[4] and x[4] > 30][:3]
series_starts = [WEEK1, WEEK1 + timedelta(days=2), WEEK1 + timedelta(days=1)]  # last is mid-week
for si, j in enumerate(series_jobs):
    crew = install_crews[(si + 1) % len(install_crews)][0]
    per = round(j[4] / 3.0, 1)
    for seq in range(1, 4):
        day = series_starts[si] + timedelta(days=seq - 1 + (2 if (series_starts[si] + timedelta(days=seq-1)).weekday() >= 5 else 0))
        add_appt(j[0], crew, day, seq, 3, per, "WORKING" if seq == 1 else "SCHEDULED")

# Spread remaining scheduled jobs lightly across other crews / days for balance contrast.
used = {r.split("'")[1] for r in appt_rows}  # crude: skip; place the rest one-per-day
rest = [x for x in schedulable if uid("appt", f"{x[0]}:1") not in used][:8]
for k, j in enumerate(rest):
    crew = install_crews[k % len(install_crews)][0]
    day = WEEK1 + timedelta(days=(k % 5))
    add_appt(j[0], crew, day, 1, 1, j[4], "SCHEDULED")

if appt_rows:
    emit("insert into sched_appointment (id, org_id, job_id, sequence, total_in_series, scheduled_start, scheduled_end, status, planned_squares, waive_trip_fee) values")
    emit(",\n".join(appt_rows) + " on conflict do nothing;\n")
    emit("insert into sched_assignment (id, org_id, appointment_id, crew_id, is_primary) values")
    emit(",\n".join(asgn_rows) + " on conflict do nothing;\n")

# ---------- Weather (6 weeks; 284/285 prefixes; rain Thursday of week 1) ----------
emit("insert into sched_weather_day (id, date, postal_prefix, precip_probability, precip_inches, wind_mph, temp_high_f, temp_low_f) values")
wrows = []
for w in range(WEEKS):
    monday = WEEK1 + timedelta(days=7 * w)
    for dow in range(7):
        day = monday + timedelta(days=dow)
        for pref in ("284", "285"):
            if w == 0 and dow == 3:      # Thursday 08-06 storm — "what breaks if it rains Thursday"
                pp, pi, wind = 80, round(random.uniform(0.6, 1.4), 2), random.randint(15, 25)
            else:
                pp = random.choices([5, 10, 20, 30, 45], weights=[40, 25, 20, 10, 5])[0]
                pi, wind = (round(random.uniform(0, 0.2), 2), random.randint(4, 12))
            hi, lo = random.randint(84, 94), random.randint(68, 76)
            wrows.append(f"  ({q(uid('wx', f'{day}:{pref}'))}, {d(day)}, {q(pref)}, {pp}, {pi}, {wind}, {hi}, {lo})")
emit(",\n".join(wrows) + " on conflict (date, postal_prefix) do nothing;\n")

emit("commit;")
print("\n".join(out))
