'use client'

/**
 * Live measurement summary for an Axis Roofing Performance v2 measurement run.
 *
 * Calls `/runs/{id}/recompute` whenever the parent says facets/edges changed
 * (debounced 600ms) and renders:
 *   - Roof totals (area, squares, predominant pitch, perimeter)
 *   - Roof line lengths (ridge / hip / valley / eave / rake), color-coded
 *   - Materials table at the selected waste %, with the full waste table
 *   - Confidence indicator
 *
 * Server is the source of truth for every number shown. Client only triggers
 * the recompute and renders results — no math happens here.
 */
import { Fragment, useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { api } from '@/lib/api'
import type { VendorOption } from '@/types'
import RoofScanSpinner from '@/components/roof-v2/RoofScanSpinner'

interface Aggregates {
  total_plan_sqft?: number
  total_roof_sqft?: number
  squares?: number
  predominant_pitch?: string
  predominant_pitch_degrees?: number
  facet_count?: number
  ridges_ft?: number
  hips_ft?: number
  valleys_ft?: number
  eaves_ft?: number
  rakes_ft?: number
  perimeter_ft?: number
  ridge_total_ft?: number
  complexity_score?: number
  waste_pct_default?: number
  confidence?: number
  wall_intersection_ft?: number
}

interface MaterialsResponse {
  lines: Array<{
    sku: string
    item_name: string
    category: string
    unit: string
    base_quantity: number
    waste_quantities: Record<string, number>
    unit_cost: number
    total_cost_at_default_waste: number
    computation_trace: string
  }>
  summary: {
    per_waste_totals: Record<string, number>
    per_category: Record<string, { items: number; subtotal: number }>
    line_count: number
  }
  grand_total_at_selected_waste: number
  totals_input: Record<string, number | string>
  waste_table: number[]
  waste_pct: number
  my_prices?: Record<string, number>
}

interface Props {
  runId: string
  geometryStamp: number       // bump to trigger a recompute (debounced)
  onConfidenceChange?: (c: number) => void
  /** Why confidence is capped, and whether the trace looks partial — both are
   *  already computed by the backend and were being thrown away here. */
  onIssuesChange?: (blocking: string[], partialSignals: string[]) => void
  /** Roof lines with no type yet. While > 0 the confidence badge shows a neutral
   *  'Labeling…' state — a mid-workflow 40% is accurate but reads as failure.
   *  Counted in distinct lines (see `edgeGeometry.ts`), not stored edge rows. */
  unlabeledCount?: number
  /** Roof lines that have a type but no sign-off. Kept separate from
   *  `unlabeledCount` so the panel never asks you to confirm an edge that has
   *  nothing to confirm, or to label one that is already labeled. */
  unconfirmedCount?: number
  /** A finalized run shows its saved numbers immediately — the confirm-edges gate
   *  only applies while actively labeling a new, unconfirmed roof. */
  runConfirmed?: boolean
  onForceSave?: () => void | Promise<void>   // optional: lets the parent force-save + recompute
  /** Project ZIP — regionalizes live price checks. */
  zip?: string
  /** Project city — localizes the "compare prices" vendor search. */
  city?: string
}

const COLORS: Record<string, string> = {
  ridges: '#a78bfa',
  hips: '#34d399',
  valleys: '#f87171',
  eaves: '#fb923c',
  rakes: '#60a5fa',
  perimeter: '#fbbf24',
}

function fmtFt(v: number | undefined): string {
  return v == null ? '—' : `${v.toLocaleString(undefined, { maximumFractionDigits: 1 })} lf`
}
function fmtSf(v: number | undefined): string {
  return v == null ? '—' : `${v.toLocaleString(undefined, { maximumFractionDigits: 0 })} sf`
}
function fmt$(v: number | undefined): string {
  return v == null ? '—' : v.toLocaleString(undefined, { style: 'currency', currency: 'USD' })
}

/** Download the material list as a supplier-ready CSV (ABC/SRS/Beacon ordering
 *  desks all take a line-item CSV/email). Quantities use the SELECTED waste %. */
function exportSupplierCsv(materials: MaterialsResponse, wastePct: number) {
  const esc = (v: string | number) => {
    const s = String(v ?? '')
    return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s
  }
  const rows: string[] = [
    ['SKU', 'Item', 'Category', `Order Qty (${wastePct}% waste)`, 'Unit', 'Base Qty', 'Unit Cost', 'Subtotal', 'Basis'].map(esc).join(','),
  ]
  for (const l of materials.lines) {
    const orderQty = l.waste_quantities?.[String(wastePct)] ?? l.base_quantity
    rows.push([
      l.sku, l.item_name, l.category.replace(/_/g, ' '), orderQty, l.unit,
      l.base_quantity, l.unit_cost.toFixed(2),
      (orderQty * l.unit_cost).toFixed(2), l.computation_trace,
    ].map(esc).join(','))
  }
  rows.push('')
  rows.push(esc(`Total @ ${wastePct}% waste: $${materials.grand_total_at_selected_waste.toFixed(2)} — generated by Axis Roofing Performance`))
  const blob = new Blob([rows.join('\n')], { type: 'text/csv;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `axis-material-order-${new Date().toISOString().slice(0, 10)}.csv`
  a.click()
  setTimeout(() => URL.revokeObjectURL(url), 5000)
}

/** One-click buy: deep-link each line to real retail search pages. Roofers buy
 *  supply-house items via the CSV export; retail links cover the rest (boots,
 *  sealant, drip edge) and make every line actionable. */
function buyUrl(itemName: string, retailer: 'hd' | 'lowes'): string {
  const q = encodeURIComponent(itemName.replace(/\(.*?\)/g, '').trim())
  return retailer === 'hd'
    ? `https://www.homedepot.com/s/${q}`
    : `https://www.lowes.com/search?searchTerm=${q}`
}

function confidenceTag(c: number | undefined) {
  const v = (c ?? 0) * 100
  if (v >= 80) return { label: 'High', cls: 'bg-emerald-500/20 text-emerald-800 border-emerald-400/40' }
  if (v >= 55) return { label: 'Moderate', cls: 'bg-amber-500/20 text-amber-800 border-amber-400/40' }
  return { label: 'Low', cls: 'bg-rose-500/20 text-rose-800 border-rose-400/40' }
}

/**
 * Says exactly what's outstanding, in the same words as the action that clears
 * it. "Needs labeling" and "needs confirming" are different jobs in different
 * places, and reporting one as the other sends the contractor hunting for work
 * that isn't there.
 */
function EdgeWorkRemaining({ unlabeled, unconfirmed }: { unlabeled: number; unconfirmed: number }) {
  const line = (n: number) => `${n} roof line${n === 1 ? '' : 's'}`
  const parts: string[] = []
  if (unlabeled > 0) parts.push(`${line(unlabeled)} still need${unlabeled === 1 ? 's' : ''} labeling`)
  if (unconfirmed > 0) parts.push(`${line(unconfirmed)} labeled but not confirmed`)
  if (parts.length === 0) return null
  return <>{parts.join(' · ')}.</>
}

export function MeasurementsSummary({ runId, geometryStamp, onConfidenceChange, onIssuesChange, onForceSave, unlabeledCount = 0, unconfirmedCount = 0, runConfirmed = false, zip, city }: Props) {
  // Anything still standing between the contractor and final numbers.
  const pendingCount = unlabeledCount + unconfirmedCount
  const [aggregates, setAggregates] = useState<Aggregates | null>(null)
  const [materials, setMaterials] = useState<MaterialsResponse | null>(null)
  const [wastePct, setWastePct] = useState<number>(12)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const lastStampRef = useRef<number>(-1)
  // Price book editing + live price checks (per SKU)
  const [priceEdit, setPriceEdit] = useState<{ sku: string; value: string } | null>(null)
  const [liveChecks, setLiveChecks] = useState<Record<string, { loading?: boolean; price?: number; source?: string; url?: string; isLive?: boolean }>>({})

  const saveMyPrice = useCallback(async (sku: string, value: string) => {
    const v = value.trim() === '' ? null : parseFloat(value)
    if (v !== null && (!Number.isFinite(v) || v < 0)) return
    try {
      await api.roofing.v2.setMyPrice(sku, v)
      setPriceEdit(null)
      await fetchAllRef.current?.()
    } catch { /* surfaced via refetch state */ }
  }, [])

  // Per-item "compare prices" dropdown: on expand, search real vendor options
  // (product-page retail links + local trade-distributor quote links), the same
  // pattern the blueprint takeoff uses. Lazy — only fetched when a row is opened.
  const [vendors, setVendors] = useState<Record<string, { open: boolean; loading: boolean; options?: VendorOption[] }>>({})
  const toggleVendors = useCallback((sku: string, itemName: string, category: string, unitCost: number) => {
    setVendors(prev => {
      const cur = prev[sku]
      if (cur?.open) return { ...prev, [sku]: { ...cur, open: false } }
      if (cur?.options) return { ...prev, [sku]: { ...cur, open: true } }
      // First open → fetch.
      api.materials.searchPrices({ item_name: itemName, category, unit_cost: unitCost, region: '', city: city || '' })
        .then(r => setVendors(p => ({ ...p, [sku]: { open: true, loading: false, options: r.options } })))
        .catch(() => setVendors(p => ({ ...p, [sku]: { open: true, loading: false, options: [] } })))
      return { ...prev, [sku]: { open: true, loading: true } }
    })
  }, [city])

  const checkLive = useCallback(async (sku: string, item: string, basePrice: number) => {
    setLiveChecks(prev => ({ ...prev, [sku]: { loading: true } }))
    try {
      const r = await api.roofing.v2.liveMaterialPrice(item, basePrice, zip)
      setLiveChecks(prev => ({ ...prev, [sku]: {
        price: r.adjusted_price, source: r.source, url: r.source_url, isLive: r.is_live,
      } }))
    } catch {
      setLiveChecks(prev => ({ ...prev, [sku]: {} }))
    }
  }, [zip])
  const fetchAllRef = useRef<(() => Promise<void>) | null>(null)

  const fetchAll = useCallback(async (waste: number) => {
    if (!runId) return
    setLoading(true)
    setError(null)
    try {
      const agg = await api.roofing.v2.recompute(runId)
      setAggregates(agg as Aggregates)
      const conf = (agg as Aggregates).confidence
      if (conf !== undefined) onConfidenceChange?.(conf)
      const a = agg as unknown as { blocking_issues?: string[]; partial_signals?: string[] }
      onIssuesChange?.(a.blocking_issues ?? [], a.partial_signals ?? [])
      try {
        const mats = await api.roofing.v2.getMaterials(runId, waste)
        setMaterials(mats as MaterialsResponse)
      } catch (err) {
        // Materials require non-zero totals; that's fine before edges are labeled.
        setMaterials(null)
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to recompute')
    } finally {
      setLoading(false)
    }
  }, [runId, onConfidenceChange, onIssuesChange])

  useEffect(() => { fetchAllRef.current = () => fetchAll(wastePct) }, [fetchAll, wastePct])

  // Debounced recompute on geometry change
  useEffect(() => {
    if (geometryStamp === lastStampRef.current) return
    lastStampRef.current = geometryStamp
    const handle = setTimeout(() => { void fetchAll(wastePct) }, 600)
    return () => clearTimeout(handle)
  }, [geometryStamp, wastePct, fetchAll])

  // When waste % changes, refetch materials only (cheaper than recompute)
  const onWasteChange = useCallback(async (pct: number) => {
    setWastePct(pct)
    if (!runId) return
    setLoading(true)
    try {
      const mats = await api.roofing.v2.getMaterials(runId, pct)
      setMaterials(mats as MaterialsResponse)
    } catch {
      setMaterials(null)
    } finally {
      setLoading(false)
    }
  }, [runId])

  const conf = pendingCount > 0
    ? { label: 'Labeling…', cls: 'bg-[#d4d4d2] text-[#2d2d2d] border-slate-500/40' }
    : confidenceTag(aggregates?.confidence)
  const hasNoData = aggregates && (aggregates.facet_count ?? 0) === 0 && !loading

  const lineBars = useMemo(() => {
    if (!aggregates) return null
    const items: Array<{ key: keyof typeof COLORS; label: string; value: number | undefined }> = [
      { key: 'ridges', label: 'Ridges', value: aggregates.ridges_ft },
      { key: 'hips', label: 'Hips', value: aggregates.hips_ft },
      { key: 'valleys', label: 'Valleys', value: aggregates.valleys_ft },
      { key: 'eaves', label: 'Eaves', value: aggregates.eaves_ft },
      { key: 'rakes', label: 'Rakes', value: aggregates.rakes_ft },
    ]
    const max = Math.max(1, ...items.map(i => i.value || 0))
    return (
      <ul className="space-y-2">
        {items.map(item => {
          const pct = ((item.value || 0) / max) * 100
          return (
            <li key={item.key}>
              <div className="flex justify-between text-xs text-[#2d2d2d]">
                <span className="flex items-center gap-2">
                  <span className="inline-block h-2 w-3 rounded" style={{ background: COLORS[item.key] }} />
                  {item.label}
                </span>
                <span className="font-mono">{fmtFt(item.value)}</span>
              </div>
              <div className="h-1.5 overflow-hidden rounded-full bg-[#eeeeed]">
                <div className="h-full rounded-full" style={{ width: `${pct}%`, background: COLORS[item.key] }} />
              </div>
            </li>
          )
        })}
      </ul>
    )
  }, [aggregates])

  // #7: measurements, roof lines, and the material list stay hidden until every
  // edge is confirmed/denied/changed — so nobody quotes off unreviewed AI labels.
  // A finalized (confirmed) roof always shows its saved numbers on revisit, so you
  // never re-label a roof you already finished.
  if (pendingCount > 0 && !runConfirmed) {
    return (
      <div className="space-y-4">
        <div className="flex items-center gap-4 rounded-xl border border-amber-400/30 bg-amber-500/10 p-4">
          <RoofScanSpinner size={46} className="flex-shrink-0" />
          <div>
            <div className="text-sm font-semibold text-amber-900">Confirm your edges to unlock the numbers</div>
            <p className="mt-0.5 text-xs leading-relaxed text-amber-900/80">
              Measurements, roof-line lengths, and the material list stay hidden until every edge is
              confirmed. Trace each plane, hit <strong>✨ Auto-label edges</strong>, then accept or fix each one.
              <span className="mt-1 block text-amber-800/90"><EdgeWorkRemaining unlabeled={unlabeledCount} unconfirmed={unconfirmedCount} /></span>
            </p>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="space-y-4">
      {hasNoData && (
        <div className="space-y-2 rounded-lg border border-amber-400/40 bg-amber-50 p-3 text-sm text-amber-900">
          <div>
            <strong>No facets saved to the database yet.</strong>
            {' '}
            Draw at least one polygon in the editor above — the panel will auto-update within a second.
          </div>
          {onForceSave && (
            <button
              onClick={async () => { await onForceSave(); await fetchAll(wastePct) }}
              className="rounded bg-blue-600 px-3 py-1.5 text-xs font-medium text-white hover:bg-blue-500"
            >Force save + recompute now</button>
          )}
        </div>
      )}
      {!hasNoData && onForceSave && (
        <div className="flex justify-end">
          <button
            onClick={async () => { await onForceSave(); await fetchAll(wastePct) }}
            disabled={loading}
            className="rounded bg-[#e4e4e2] px-2 py-1 text-[10px] text-[#1a1a1a] hover:bg-[#d4d4d2] disabled:opacity-50"
            title="Bypass the debounce and force an immediate save + recompute"
          >↻ Save & recompute now</button>
        </div>
      )}
      {/* Live/not-final banner. The spinner keeps turning until the numbers are
          BOTH done computing (loading === false) AND final (all edges labeled).
          While recomputing we say so; once settled but unlabeled, we prompt for
          edge confirmation. It only disappears when the totals are real. */}
      {(loading || pendingCount > 0) && (
        <div className="flex items-center gap-4 rounded-xl border border-amber-400/30 bg-amber-500/10 p-4">
          <RoofScanSpinner size={46} className="flex-shrink-0" />
          {loading ? (
            <div>
              <div className="text-sm font-semibold text-amber-900">Crunching the latest measurements…</div>
              <p className="mt-0.5 text-xs leading-relaxed text-amber-900/80">
                Roof area, roof-line lengths, confidence, and the material list are updating from your last edit.
                Hang tight — the numbers below settle the moment this finishes.
              </p>
            </div>
          ) : (
            <div>
              <div className="text-sm font-semibold text-amber-900">These numbers aren&apos;t final yet</div>
              <p className="mt-0.5 text-xs leading-relaxed text-amber-900/80">
                Roof-line lengths, true roof area, confidence, and the material list stay <strong>provisional</strong> until
                you confirm the edges. Trace every plane, then hit <strong>✨ Auto-label edges</strong> and accept or fix
                each one — the totals lock in the moment you do.
                <span className="mt-1 block text-amber-800/90"><EdgeWorkRemaining unlabeled={unlabeledCount} unconfirmed={unconfirmedCount} /></span>
              </p>
            </div>
          )}
        </div>
      )}

      {/* Top totals */}
      <div className="grid grid-cols-2 gap-3 md:grid-cols-4">
        <Card label="True roof area" value={fmtSf(aggregates?.total_roof_sqft)} sub="(slope-adjusted)" />
        <Card label="Roofing squares" value={aggregates?.squares != null ? `${aggregates.squares.toFixed(2)} sq` : '—'} sub="area ÷ 100" />
        <Card label="Predominant pitch" value={aggregates?.predominant_pitch ?? '—'} sub={aggregates?.predominant_pitch_degrees ? `${aggregates.predominant_pitch_degrees.toFixed(1)}°` : ''} />
        <Card label="Confidence" value={<span className={`inline-block rounded border px-2 py-0.5 text-xs ${conf.cls}`}>{conf.label} ({((aggregates?.confidence ?? 0) * 100).toFixed(0)}%)</span>} sub="area-weighted across facets" />
      </div>

      <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
        {/* Roof lines */}
        <section className="rounded-lg border border-[#dededc] bg-[#f8f8f7] p-4">
          <h3 className="mb-3 text-sm font-semibold text-[#1a1a1a]">Roof line measurements</h3>
          {lineBars || <p className="text-xs text-[#6b7280]">Draw and label facet edges to see roof lines.</p>}
          {aggregates && (
            <div className="mt-3 border-t border-[#dededc] pt-3 text-xs text-[#6b7280]">
              Perimeter: <span className="font-mono text-[#1a1a1a]">{fmtFt(aggregates.perimeter_ft)}</span> &nbsp;·&nbsp;
              Ridge total: <span className="font-mono text-[#1a1a1a]">{fmtFt(aggregates.ridge_total_ft)}</span>
              {aggregates.wall_intersection_ft ? (
                <> &nbsp;·&nbsp; Wall: <span className="font-mono text-[#1a1a1a]">{fmtFt(aggregates.wall_intersection_ft)}</span></>
              ) : null}
            </div>
          )}
        </section>

        {/* Waste & complexity */}
        <section className="rounded-lg border border-[#dededc] bg-[#f8f8f7] p-4">
          <h3 className="mb-3 text-sm font-semibold text-[#1a1a1a]">Waste calculation</h3>
          <div className="mb-3 text-xs text-[#6b7280]">
            Complexity score: <span className="font-mono text-[#1a1a1a]">{aggregates?.complexity_score?.toFixed(2) ?? '—'}</span>
            &nbsp;·&nbsp; Recommended: <span className="font-mono text-[#1a1a1a]">{aggregates?.waste_pct_default ?? '—'}%</span>
          </div>
          <div className="flex flex-wrap gap-2">
            {(materials?.waste_table ?? [5, 10, 12, 15, 18, 20, 25]).map(pct => (
              <button
                key={pct}
                onClick={() => onWasteChange(pct)}
                className={`rounded-md border px-3 py-1.5 text-xs font-medium transition ${ wastePct === pct ? 'border-blue-400 bg-blue-500/30 text-white' : 'border-[#dededc] bg-[#eeeeed] text-[#2d2d2d] hover:bg-[#e4e4e2]' }`}
              >
                {pct}%
                {materials?.summary.per_waste_totals?.[pct] !== undefined && (
                  <span className="ml-1 text-[#6b7280]">→ {fmt$(materials.summary.per_waste_totals[pct])}</span>
                )}
              </button>
            ))}
          </div>
        </section>
      </div>

      {/* Materials */}
      <section className="rounded-lg border border-[#dededc] bg-[#f8f8f7] p-4">
        <div className="mb-3 flex items-center justify-between gap-2">
          <h3 className="text-sm font-semibold text-[#1a1a1a]">Material ordering list ({wastePct}% waste)</h3>
          <div className="flex items-center gap-2">
            {materials && materials.lines.length > 0 && (
              <button
                onClick={() => exportSupplierCsv(materials, wastePct)}
                title="Download this list as a CSV formatted for your supplier's ordering desk (ABC / SRS / Beacon)"
                className="rounded bg-blue-600 px-2.5 py-1 text-[11px] font-semibold text-white hover:bg-blue-500"
              >⬇ Supplier CSV</button>
            )}
            <span className="text-sm font-semibold text-emerald-800">{fmt$(materials?.grand_total_at_selected_waste)}</span>
          </div>
        </div>
        {materials && materials.lines.length > 0 && (
          <p className="mb-2 text-[10px] text-[#6b7280]">
            Click a price to set your dealer rate (<span className="mx-0.5 inline-block h-1.5 w-1.5 rounded-full bg-emerald-400 align-middle" /> = yours) · hover a row for buy links &amp; live price
          </p>
        )}
        {!materials && (
          <p className="text-xs text-[#6b7280]">
            Once facet edges are labeled and totals are non-zero, materials appear here.
          </p>
        )}
        {materials && materials.lines.length > 0 && (
          <div className="overflow-x-auto">
            <table className="w-full text-xs">
              <thead>
                <tr className="border-b border-[#dededc] text-[#6b7280]">
                  <th className="px-2 py-2 text-left">SKU</th>
                  <th className="px-2 py-2 text-left">Item</th>
                  <th className="px-2 py-2 text-right">Base qty</th>
                  <th className="px-2 py-2 text-right">Qty @ {wastePct}%</th>
                  <th className="px-2 py-2 text-left">Unit</th>
                  <th className="px-2 py-2 text-right">Unit $</th>
                  <th className="px-2 py-2 text-right">Subtotal</th>
                </tr>
              </thead>
              <tbody>
                {materials.lines.map(line => (
                  <Fragment key={line.sku}>
                  <tr className="group border-b border-[#dededc] text-[#1a1a1a]">
                    <td className="px-2 py-2 font-mono text-[10px] text-[#6b7280]">{line.sku}</td>
                    <td className="px-2 py-2">
                      <div className="flex flex-wrap items-center gap-2">
                        <span>{line.item_name}</span>
                        <button onClick={() => toggleVendors(line.sku, line.item_name, line.category, line.unit_cost)}
                          className="inline-flex items-center gap-1 rounded-full border border-blue-400/30 bg-blue-50 px-2 py-0.5 text-[10px] font-semibold text-blue-800 hover:bg-blue-500/20"
                          title="Find where to buy this + compare local prices">
                          🛒 Buy / compare {vendors[line.sku]?.open ? '▴' : '▾'}
                        </button>
                      </div>
                      <div className="text-[10px] text-[#6b7280]">{line.computation_trace}</div>
                    </td>
                    <td className="px-2 py-2 text-right font-mono">{line.base_quantity.toFixed(2)}</td>
                    <td className="px-2 py-2 text-right font-mono">{line.waste_quantities[wastePct] ?? '—'}</td>
                    <td className="px-2 py-2">{line.unit}</td>
                    <td className="px-2 py-2 text-right font-mono">
                      {priceEdit?.sku === line.sku ? (
                        <input
                          autoFocus
                          type="number" step="0.01" min="0"
                          value={priceEdit.value}
                          onChange={e => setPriceEdit({ sku: line.sku, value: e.target.value })}
                          onKeyDown={e => {
                            if (e.key === 'Enter') void saveMyPrice(line.sku, priceEdit.value)
                            if (e.key === 'Escape') setPriceEdit(null)
                          }}
                          onBlur={() => void saveMyPrice(line.sku, priceEdit.value)}
                          className="w-20 rounded border border-blue-500 bg-[#eeeeed] px-1 py-0.5 text-right text-[#1a1a1a]"
                        />
                      ) : (
                        <button
                          onClick={() => setPriceEdit({ sku: line.sku, value: String(line.unit_cost) })}
                          title={materials.my_prices?.[line.sku] != null
                            ? 'Your price (from your price book) — click to change, clear to reset'
                            : 'National average — click to set YOUR dealer price'}
                          className="group/price inline-flex items-center gap-1 hover:text-blue-800"
                        >
                          {materials.my_prices?.[line.sku] != null && (
                            <span className="h-1.5 w-1.5 rounded-full bg-emerald-400" title="Your price" />
                          )}
                          {fmt$(line.unit_cost)}
                          <span className="w-3 text-[9px] opacity-0 transition-opacity group-hover:opacity-60">✎</span>
                        </button>
                      )}
                    </td>
                    <td className="px-2 py-2 text-right font-mono">{fmt$((line.waste_quantities[wastePct] ?? 0) * line.unit_cost)}</td>
                  </tr>
                  {vendors[line.sku]?.open && (
                    <tr key={line.sku + '-vendors'} className="border-b border-[#dededc] bg-[#f8f8f7]">
                      <td colSpan={7} className="px-3 py-2.5">
                        {vendors[line.sku]?.loading ? (
                          <div className="flex items-center gap-2 text-[11px] text-[#6b7280]">
                            <span className="h-3 w-3 animate-spin rounded-full border-2 border-blue-400 border-t-transparent" />
                            Finding where to buy {line.item_name}{city ? ` near ${city}` : ''}…
                          </div>
                        ) : (vendors[line.sku]?.options?.length ?? 0) === 0 ? (
                          <div className="flex flex-wrap items-center gap-3 text-[11px] text-[#6b7280]">
                            <span>No product pages found. Try the big-box search:</span>
                            <a href={buyUrl(line.item_name, 'hd')} target="_blank" rel="noreferrer" className="font-semibold text-orange-800 hover:underline">Home Depot ↗</a>
                            <a href={buyUrl(line.item_name, 'lowes')} target="_blank" rel="noreferrer" className="font-semibold text-blue-800 hover:underline">Lowe&apos;s ↗</a>
                          </div>
                        ) : (
                          <div>
                            <div className="mb-1.5 text-[10px] font-semibold uppercase tracking-wide text-[#6b7280]">
                              Where to buy · compare prices{city ? ` near ${city}` : ''}
                            </div>
                            <div className="grid gap-1.5 sm:grid-cols-2">
                              {vendors[line.sku]!.options!.map((o, i) => (
                                <a key={i} href={o.url} target="_blank" rel="noreferrer"
                                  className="flex items-center justify-between gap-2 rounded-lg border border-[#dededc] bg-[#eeeeed] px-2.5 py-1.5 hover:border-blue-400/40 hover:bg-[#eeeeed]">
                                  <span className="flex min-w-0 items-center gap-1.5">
                                    {o.is_local && <span className="rounded bg-emerald-500/20 px-1 py-0.5 text-[9px] font-semibold text-emerald-800">LOCAL</span>}
                                    <span className="truncate text-[11px] text-[#1a1a1a]">{o.vendor}</span>
                                  </span>
                                  <span className="shrink-0 text-[11px] font-semibold text-[#1a1a1a]">
                                    {o.quote_only || o.price == null ? <span className="text-blue-800">Get quote ↗</span> : <>{fmt$(o.price)} ↗</>}
                                  </span>
                                </a>
                              ))}
                            </div>
                          </div>
                        )}
                        {/* Always offer direct big-box search — Home Depot AND Lowe's —
                            even when a live product page wasn't matched. */}
                        <div className="mt-2 flex flex-wrap items-center gap-3 border-t border-[#dededc] pt-2 text-[11px] text-[#6b7280]">
                          <span>Search directly:</span>
                          <a href={buyUrl(line.item_name, 'hd')} target="_blank" rel="noreferrer" className="font-semibold text-orange-800 hover:underline">Home Depot ↗</a>
                          <a href={buyUrl(line.item_name, 'lowes')} target="_blank" rel="noreferrer" className="font-semibold text-blue-800 hover:underline">Lowe&apos;s ↗</a>
                        </div>
                      </td>
                    </tr>
                  )}
                  </Fragment>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </section>

      {loading && <p className="text-xs text-[#6b7280]">Recomputing…</p>}
      {error && <p className="text-xs text-rose-400">{error}</p>}
    </div>
  )
}

function Card({ label, value, sub }: { label: string; value: React.ReactNode; sub?: string }) {
  return (
    <div className="rounded-lg border border-[#dededc] bg-[#f8f8f7] p-3">
      <div className="text-[10px] uppercase tracking-wide text-[#6b7280]">{label}</div>
      <div className="mt-1 text-lg font-semibold text-[#1a1a1a]">{value}</div>
      {sub && <div className="text-[10px] text-[#6b7280]">{sub}</div>}
    </div>
  )
}

export default MeasurementsSummary
