export const STATES: { code: string; name: string }[] = [
  { code: 'AL', name: 'Alabama' },
  { code: 'AK', name: 'Alaska' },
  { code: 'AZ', name: 'Arizona' },
  { code: 'AR', name: 'Arkansas' },
  { code: 'CA', name: 'California' },
  { code: 'CO', name: 'Colorado' },
  { code: 'CT', name: 'Connecticut' },
  { code: 'DE', name: 'Delaware' },
  { code: 'FL', name: 'Florida' },
  { code: 'GA', name: 'Georgia' },
  { code: 'HI', name: 'Hawaii' },
  { code: 'ID', name: 'Idaho' },
  { code: 'IL', name: 'Illinois' },
  { code: 'IN', name: 'Indiana' },
  { code: 'IA', name: 'Iowa' },
  { code: 'KS', name: 'Kansas' },
  { code: 'KY', name: 'Kentucky' },
  { code: 'LA', name: 'Louisiana' },
  { code: 'ME', name: 'Maine' },
  { code: 'MD', name: 'Maryland' },
  { code: 'MA', name: 'Massachusetts' },
  { code: 'MI', name: 'Michigan' },
  { code: 'MN', name: 'Minnesota' },
  { code: 'MS', name: 'Mississippi' },
  { code: 'MO', name: 'Missouri' },
  { code: 'MT', name: 'Montana' },
  { code: 'NE', name: 'Nebraska' },
  { code: 'NV', name: 'Nevada' },
  { code: 'NH', name: 'New Hampshire' },
  { code: 'NJ', name: 'New Jersey' },
  { code: 'NM', name: 'New Mexico' },
  { code: 'NY', name: 'New York' },
  { code: 'NC', name: 'North Carolina' },
  { code: 'ND', name: 'North Dakota' },
  { code: 'OH', name: 'Ohio' },
  { code: 'OK', name: 'Oklahoma' },
  { code: 'OR', name: 'Oregon' },
  { code: 'PA', name: 'Pennsylvania' },
  { code: 'RI', name: 'Rhode Island' },
  { code: 'SC', name: 'South Carolina' },
  { code: 'SD', name: 'South Dakota' },
  { code: 'TN', name: 'Tennessee' },
  { code: 'TX', name: 'Texas' },
  { code: 'UT', name: 'Utah' },
  { code: 'VT', name: 'Vermont' },
  { code: 'VA', name: 'Virginia' },
  { code: 'WA', name: 'Washington' },
  { code: 'WV', name: 'West Virginia' },
  { code: 'WI', name: 'Wisconsin' },
  { code: 'WY', name: 'Wyoming' },
]

export const COUNTIES: Record<string, string[]> = {
  AL: ['Jefferson','Mobile','Madison','Montgomery','Shelby','Baldwin','Tuscaloosa','Lee','Calhoun','Etowah','Houston','Marshall','Morgan','DeKalb','Limestone'],
  AK: ['Anchorage','Fairbanks North Star','Matanuska-Susitna','Kenai Peninsula','Juneau','Bethel','Kodiak Island','Yukon-Koyukuk','Nome','Kusilvak'],
  AZ: ['Maricopa','Pima','Pinal','Yavapai','Mohave','Yuma','Coconino','Navajo','Apache','Graham','Santa Cruz','Gila','La Paz','Greenlee'],
  AR: ['Pulaski','Benton','Washington','Sebastian','Faulkner','Saline','Garland','Craighead','Mississippi','White','Lonoke','Union','Miller','Carroll'],
  CA: ['Los Angeles','San Diego','Orange','Riverside','San Bernardino','Santa Clara','Alameda','Sacramento','Contra Costa','Fresno','Kern','San Francisco','Ventura','San Mateo','San Joaquin','Stanislaus','Sonoma','Tulare','Solano','Monterey','Santa Barbara','Placer','San Luis Obispo','Marin','Shasta','El Dorado','Merced','Butte','Yolo','Napa'],
  CO: ['El Paso','Denver','Jefferson','Arapahoe','Adams','Larimer','Douglas','Boulder','Weld','Pueblo','Mesa','Broomfield','Garfield','Eagle','La Plata','Fremont','Delta','Montrose','Summit','Routt'],
  CT: ['Fairfield','Hartford','New Haven','Middlesex','Tolland','Windham','New London','Litchfield'],
  DE: ['New Castle','Sussex','Kent'],
  FL: ['Miami-Dade','Broward','Palm Beach','Hillsborough','Orange','Pinellas','Duval','Lee','Polk','Brevard','Volusia','Pasco','Seminole','Sarasota','Manatee','Collier','Marion','Osceola','Alachua','St. Lucie','Leon','Lake','Hernando','Escambia','Clay','Bay','Charlotte','St. Johns','Okaloosa','Flagler'],
  GA: ['Fulton','Gwinnett','Cobb','DeKalb','Cherokee','Clayton','Forsyth','Henry','Hall','Richmond','Chatham','Columbia','Carroll','Bibb','Newton','Coweta','Paulding','Houston','Muscogee','Lowndes','Fayette','Douglas','Walton','Rockdale','Dougherty'],
  HI: ['Honolulu','Hawaii','Maui','Kauai','Kalawao'],
  ID: ['Ada','Canyon','Kootenai','Twin Falls','Bannock','Bonner','Bonneville','Nez Perce','Cassia','Jefferson','Madison','Bingham','Blaine','Elmore','Payette'],
  IL: ['Cook','DuPage','Lake','Will','Kane','McHenry','Winnebago','Madison','St. Clair','Champaign','Sangamon','Peoria','McLean','Rock Island','Tazewell','Macon','Kankakee','Whiteside','LaSalle','DeKalb'],
  IN: ['Marion','Lake','Allen','Hamilton','St. Joseph','Tippecanoe','Elkhart','Johnson','Vanderburgh','Delaware','Monroe','Madison','Hendricks','Vigo','Howard','Clark','Floyd','Bartholomew','Porter','Boone'],
  IA: ['Polk','Linn','Scott','Johnson','Black Hawk','Woodbury','Story','Dallas','Pottawattamie','Dubuque','Marion','Warren','Marshall','Clinton','Des Moines','Cerro Gordo','Webster','Muscatine','Jasper','Henry'],
  KS: ['Johnson','Sedgwick','Shawnee','Wyandotte','Douglas','Riley','Leavenworth','Reno','Butler','Harvey','Saline','Crawford','Finney','Ellis','Montgomery'],
  KY: ['Jefferson','Fayette','Kenton','Boone','Warren','Campbell','Hardin','Madison','Daviess','McCracken','Laurel','Oldham','Christian','Franklin','Clark'],
  LA: ['East Baton Rouge','Jefferson','Orleans','St. Tammany','Caddo','Calcasieu','Lafayette','Rapides','Terrebonne','Ascension','St. Landry','Ouachita','Lafourche','Beauregard','Bossier'],
  ME: ['Cumberland','York','Penobscot','Kennebec','Androscoggin','Knox','Oxford','Somerset','Aroostook','Hancock','Sagadahoc','Lincoln','Waldo','Piscataquis','Franklin','Washington'],
  MD: ['Montgomery','Prince George\'s','Baltimore','Anne Arundel','Howard','Frederick','Baltimore City','Charles','Carroll','Harford','Washington','Calvert','St. Mary\'s','Wicomico','Cecil'],
  MA: ['Middlesex','Worcester','Essex','Suffolk','Norfolk','Bristol','Plymouth','Hampden','Hampshire','Barnstable','Berkshire','Franklin','Dukes','Nantucket'],
  MI: ['Wayne','Oakland','Macomb','Kent','Genesee','Washtenaw','Ingham','Kalamazoo','Ottawa','Saginaw','Jackson','Livingston','Muskegon','St. Clair','Monroe','Bay','Berrien','Lapeer','Calhoun','Allegan'],
  MN: ['Hennepin','Ramsey','Dakota','Anoka','Washington','Scott','Sherburne','Wright','Olmsted','St. Louis','Stearns','Rice','Carver','Blue Earth','Crow Wing'],
  MS: ['Hinds','Harrison','DeSoto','Madison','Rankin','Forrest','Jackson','Lee','Lamar','Lowndes','Warren','George','Jones','Pike','Marshall'],
  MO: ['St. Louis','Jackson','St. Charles','Greene','Jefferson','Clay','Cass','Boone','St. Louis City','Franklin','Christian','Jasper','St. Francois','Cole','Newton'],
  MT: ['Yellowstone','Cascade','Missoula','Gallatin','Lake','Flathead','Ravalli','Hill','Lewis and Clark','Silver Bow','Rosebud','Carbon','Toole','Richland','Roosevelt'],
  NE: ['Douglas','Lancaster','Sarpy','Hall','Buffalo','Dodge','Platte','Madison','Lincoln','Dawson','Scotts Bluff','Cass','York','Adams','Gage'],
  NV: ['Clark','Washoe','Carson City','Elko','Douglas','Lyon','Churchill','Nye','Humboldt','Lander','White Pine','Storey','Eureka','Esmeralda','Mineral'],
  NH: ['Hillsborough','Rockingham','Merrimack','Strafford','Cheshire','Carroll','Grafton','Belknap','Sullivan','Coos'],
  NJ: ['Bergen','Middlesex','Essex','Hudson','Monmouth','Union','Ocean','Morris','Passaic','Camden','Burlington','Mercer','Atlantic','Somerset','Gloucester'],
  NM: ['Bernalillo','Dona Ana','Santa Fe','Sandoval','San Juan','Chavez','Otero','Rio Arriba','Lea','Eddy','Grant','Luna','Sierra','Valencia','Taos'],
  NY: ['Kings','Queens','New York','Suffolk','Bronx','Nassau','Westchester','Erie','Monroe','Richmond','Onondaga','Orange','Rockland','Albany','Dutchess','Saratoga','Niagara','Oneida','Broome','Schenectady'],
  NC: ['Mecklenburg','Wake','Guilford','Forsyth','Cumberland','Durham','Buncombe','Union','Cabarrus','Onslow','Gaston','New Hanover','Johnston','Alamance','Pitt','Randolph','Rowan','Catawba','Iredell','Lee'],
  ND: ['Cass','Burleigh','Grand Forks','Ward','Morton','Williams','Stark','Ramsey','Traill','McLean','Richland','Stutsman','Mountrail','Barnes','Pierce'],
  OH: ['Franklin','Cuyahoga','Hamilton','Summit','Montgomery','Lucas','Butler','Stark','Lorain','Warren','Lake','Mahoning','Medina','Greene','Clermont','Delaware','Clark','Licking','Allen','Fairfield'],
  OK: ['Oklahoma','Tulsa','Cleveland','Canadian','Comanche','Wagoner','Rogers','Creek','Muskogee','Osage','Payne','Pottawatomie','Garfield','Washington','Pittsburg'],
  OR: ['Multnomah','Washington','Clackamas','Lane','Marion','Jackson','Deschutes','Linn','Douglas','Yamhill','Benton','Josephine','Columbia','Klamath','Umatilla'],
  PA: ['Philadelphia','Allegheny','Montgomery','Bucks','Delaware','Chester','Lancaster','York','Luzerne','Berks','Westmoreland','Northampton','Erie','Lehigh','Cumberland','Dauphin','Centre','Monroe','Washington','Lackawanna'],
  RI: ['Providence','Kent','Washington','Newport','Bristol'],
  SC: ['Greenville','Richland','Charleston','Horry','Spartanburg','Anderson','Lexington','Beaufort','Dorchester','Berkeley','York','Pickens','Aiken','Florence','Cherokee'],
  SD: ['Minnehaha','Pennington','Lincoln','Brown','Codington','Brookings','Meade','Hamlin','Lawrence','Hughes','Butte','Davison','Yankton','Clay'],
  TN: ['Shelby','Davidson','Knox','Hamilton','Williamson','Rutherford','Montgomery','Sumner','Blount','Madison','Sullivan','Wilson','Maury','Sevier','Robertson'],
  TX: ['Harris','Dallas','Tarrant','Bexar','Travis','Collin','Hidalgo','El Paso','Denton','Fort Bend','Montgomery','Williamson','Cameron','Nueces','Bell','Galveston','Lubbock','Jefferson','Webb','Smith','Hays','Ellis','Johnson','McLennan','Brazoria'],
  UT: ['Salt Lake','Utah','Davis','Weber','Washington','Cache','Iron','Tooele','Box Elder','Sanpete','Sevier','Millard','Kane','Duchesne','Carbon'],
  VT: ['Chittenden','Rutland','Washington','Windsor','Franklin','Addison','Orange','Lamoille','Bennington','Orleans','Caledonia','Grand Isle','Essex','Windham'],
  VA: ['Fairfax','Prince William','Loudoun','Chesterfield','Arlington','Henrico','Virginia Beach','Chesapeake','Newport News','Norfolk','Richmond City','Roanoke','Hampton','Alexandria','Suffolk','Spotsylvania','Stafford','Frederick','Augusta','Montgomery'],
  WA: ['King','Pierce','Snohomish','Spokane','Clark','Thurston','Kitsap','Whatcom','Benton','Skagit','Yakima','Cowlitz','Grant','Franklin','Grays Harbor'],
  WV: ['Kanawha','Cabell','Wood','Berkeley','Monongalia','Raleigh','Putnam','Mercer','Harrison','Greenbrier','Marshall','Wayne','Mineral','Marion','Lincoln'],
  WI: ['Milwaukee','Dane','Waukesha','Brown','Racine','Outagamie','Winnebago','Rock','Kenosha','Marathon','Washington','La Crosse','Ozaukee','Sheboygan','Polk'],
  WY: ['Laramie','Natrona','Campbell','Sweetwater','Fremont','Albany','Sheridan','Uinta','Lincoln','Park','Teton','Goshen','Platte','Carbon','Converse'],
}

// Nested by state code → county name → cities
export const CITIES: Record<string, Record<string, string[]>> = {
  AL: {
    Jefferson: ['Birmingham','Hoover','Vestavia Hills','Bessemer','Homewood','Mountain Brook','Trussville','Alabaster'],
    Mobile: ['Mobile','Prichard','Saraland','Chickasaw','Satsuma','Tillmans Corner'],
    Madison: ['Huntsville','Madison','Decatur','Harvest','Triana'],
    Montgomery: ['Montgomery','Pike Road','Millbrook','Wetumpka','Prattville'],
    Shelby: ['Helena','Alabaster','Pelham','Calera','Montevallo','Vincent'],
    Baldwin: ['Daphne','Fairhope','Foley','Gulf Shores','Orange Beach','Spanish Fort'],
    Tuscaloosa: ['Tuscaloosa','Northport','Cottondale','Moundville','Brookwood'],
    Lee: ['Auburn','Opelika','Phenix City','Smiths Station','Loachapoka'],
  },
  AK: {
    Anchorage: ['Anchorage','Eagle River','Chugiak','Girdwood'],
    'Fairbanks North Star': ['Fairbanks','North Pole','College','Ester'],
    'Matanuska-Susitna': ['Wasilla','Palmer','Big Lake','Houston','Sutton'],
    'Kenai Peninsula': ['Kenai','Homer','Soldotna','Seward','Seldovia'],
  },
  AZ: {
    Maricopa: ['Phoenix','Mesa','Chandler','Scottsdale','Glendale','Gilbert','Tempe','Peoria','Surprise','Avondale','Goodyear','Buckeye','Tolleson','El Mirage'],
    Pima: ['Tucson','Marana','Oro Valley','Sahuarita','South Tucson'],
    Pinal: ['Casa Grande','Maricopa','Apache Junction','Coolidge','Florence','Eloy'],
    Yavapai: ['Prescott','Prescott Valley','Cottonwood','Sedona','Camp Verde','Chino Valley'],
    Mohave: ['Kingman','Lake Havasu City','Bullhead City','Fort Mohave'],
    Yuma: ['Yuma','Somerton','San Luis','Wellton'],
  },
  AR: {
    Pulaski: ['Little Rock','North Little Rock','Maumelle','Jacksonville','Sherwood','Bryant'],
    Benton: ['Bentonville','Rogers','Springdale','Bella Vista','Siloam Springs'],
    Washington: ['Fayetteville','Springdale','Farmington','Prairie Grove','Elkins'],
    Sebastian: ['Fort Smith','Van Buren','Greenwood','Barling','Lavaca'],
    Faulkner: ['Conway','Vilonia','Greenbrier','Mayflower','Wooster'],
  },
  CA: {
    'Los Angeles': ['Los Angeles','Long Beach','Glendale','Santa Clarita','Lancaster','Pomona','Torrance','Pasadena','El Monte','Downey','West Covina','Norwalk','Burbank','Inglewood','Compton','Carson','Santa Monica','Hawthorne','Alhambra','Whittier'],
    'San Diego': ['San Diego','Chula Vista','Oceanside','Escondido','Carlsbad','El Cajon','Vista','San Marcos','Santee','Encinitas','National City','La Mesa','Poway','Lemon Grove'],
    Orange: ['Anaheim','Santa Ana','Irvine','Huntington Beach','Garden Grove','Fullerton','Orange','Newport Beach','Costa Mesa','Mission Viejo','Westminster'],
    Riverside: ['Riverside','Moreno Valley','Corona','Temecula','Murrieta','Menifee','Hemet','Perris','Indio','Palm Springs','Palm Desert'],
    'San Bernardino': ['San Bernardino','Fontana','Rancho Cucamonga','Ontario','Victorville','Rialto','Hesperia','Chino','Upland','Chino Hills','Apple Valley','Redlands'],
    'Santa Clara': ['San Jose','Sunnyvale','Santa Clara','Mountain View','Cupertino','Milpitas','Palo Alto','Gilroy','Campbell','Los Gatos'],
    Alameda: ['Oakland','Fremont','Hayward','Berkeley','San Leandro','Livermore','Pleasanton','Union City','Newark','Dublin'],
    Sacramento: ['Sacramento','Elk Grove','Roseville','Folsom','Citrus Heights','Rancho Cordova','Davis','West Sacramento','Woodland'],
    Fresno: ['Fresno','Clovis','Sanger','Selma','Reedley','Kerman','Coalinga'],
    Kern: ['Bakersfield','Delano','Ridgecrest','Tehachapi','McFarland','Shafter','Wasco'],
    'San Francisco': ['San Francisco'],
    Ventura: ['Oxnard','Thousand Oaks','Simi Valley','Ventura','Camarillo','Moorpark','Santa Paula'],
    'San Mateo': ['Daly City','San Mateo','Redwood City','South San Francisco','San Bruno','Pacifica','Millbrae'],
    Sonoma: ['Santa Rosa','Petaluma','Rohnert Park','Windsor','Sebastopol','Healdsburg','Cotati'],
    Placer: ['Roseville','Rocklin','Lincoln','Auburn','Loomis','Granite Bay'],
  },
  CO: {
    'El Paso': ['Colorado Springs','Fountain','Manitou Springs','Falcon','Black Forest','Security-Widefield'],
    Denver: ['Denver','Englewood','Aurora','Lakewood','Thornton','Westminster','Arvada','Commerce City'],
    Jefferson: ['Lakewood','Arvada','Westminster','Golden','Wheat Ridge','Littleton','Edgewater'],
    Arapahoe: ['Aurora','Englewood','Littleton','Centennial','Greenwood Village','Cherry Hills Village'],
    Adams: ['Thornton','Commerce City','Westminster','Brighton','Northglenn','Federal Heights'],
    Larimer: ['Fort Collins','Loveland','Berthoud','Estes Park','Wellington'],
    Douglas: ['Castle Rock','Parker','Lone Tree','Highlands Ranch','Roxborough Park'],
    Boulder: ['Boulder','Longmont','Lafayette','Louisville','Erie','Broomfield'],
    Weld: ['Greeley','Loveland','Evans','Windsor','Longmont','Johnstown','Milliken'],
    Pueblo: ['Pueblo','Pueblo West','Boone','Avondale','Beulah'],
  },
  CT: {
    Fairfield: ['Bridgeport','Stamford','Norwalk','Danbury','Greenwich','Westport','Fairfield','Trumbull','Shelton'],
    Hartford: ['Hartford','New Britain','Bristol','Meriden','West Hartford','Manchester','Enfield','Southington'],
    'New Haven': ['New Haven','Waterbury','Milford','West Haven','Hamden','Derby'],
    Middlesex: ['Middletown','Middlefield','Durham','Cromwell','Portland','East Hampton'],
    Tolland: ['Vernon','Tolland','Ellington','Coventry','Mansfield','Stafford'],
  },
  DE: {
    'New Castle': ['Wilmington','Newark','Bear','Middletown','Glasgow','Brookside','Pike Creek'],
    Sussex: ['Georgetown','Seaford','Lewes','Milford','Ocean View','Rehoboth Beach'],
    Kent: ['Dover','Milford','Smyrna','Harrington','Camden'],
  },
  FL: {
    'Miami-Dade': ['Miami','Hialeah','Miami Gardens','Miami Beach','Homestead','North Miami','Coral Gables','Doral','Aventura','Kendall','Pembroke Pines'],
    Broward: ['Fort Lauderdale','Hollywood','Pembroke Pines','Miramar','Coral Springs','Plantation','Sunrise','Pompano Beach','Davie','Weston','Deerfield Beach'],
    'Palm Beach': ['West Palm Beach','Boca Raton','Boynton Beach','Delray Beach','Jupiter','Palm Beach Gardens','Wellington','Lake Worth','Greenacres'],
    Hillsborough: ['Tampa','Brandon','Riverview','Plant City','Temple Terrace','Town n Country','Westchase'],
    Orange: ['Orlando','Winter Garden','Apopka','Ocoee','Kissimmee','Sanford','Maitland','Altamonte Springs'],
    Pinellas: ['St. Petersburg','Clearwater','Largo','Dunedin','Tarpon Springs','Safety Harbor','Seminole'],
    Duval: ['Jacksonville','Jacksonville Beach','Neptune Beach','Atlantic Beach','Baldwin'],
    Lee: ['Fort Myers','Cape Coral','Bonita Springs','Estero','Lehigh Acres'],
    Polk: ['Lakeland','Winter Haven','Haines City','Bartow','Lake Wales','Auburndale'],
    Brevard: ['Melbourne','Palm Bay','Titusville','Cocoa','Rockledge','Merritt Island'],
    Volusia: ['Daytona Beach','Deltona','Ormond Beach','Port Orange','DeLand','Edgewater'],
    Sarasota: ['Sarasota','Venice','North Port','Osprey','Englewood','Nokomis'],
    Manatee: ['Bradenton','Palmetto','Lakewood Ranch','Ellenton','Parrish','Oneco'],
    Collier: ['Naples','Marco Island','Immokalee','Bonita Springs','Golden Gate'],
    Alachua: ['Gainesville','Alachua','High Springs','Newberry','Micanopy'],
    Leon: ['Tallahassee','Havana','Midway','Woodville','Quincy'],
  },
  GA: {
    Fulton: ['Atlanta','Sandy Springs','Roswell','Johns Creek','Alpharetta','Milton','East Point','College Park'],
    Gwinnett: ['Lawrenceville','Duluth','Norcross','Snellville','Lilburn','Buford','Dacula','Suwanee'],
    Cobb: ['Marietta','Smyrna','Kennesaw','Acworth','Powder Springs','Austell'],
    DeKalb: ['Decatur','Dunwoody','Chamblee','Stone Mountain','Tucker','Brookhaven','Doraville'],
    Cherokee: ['Canton','Ball Ground','Holly Springs','Woodstock','Waleska'],
    Clayton: ['Jonesboro','Morrow','Riverdale','College Park','Forest Park','Lake City'],
    Forsyth: ['Cumming','Suwanee','Johns Creek','Alpharetta'],
    Henry: ['McDonough','Stockbridge','Hampton','Locust Grove','Ellenwood'],
    Hall: ['Gainesville','Oakwood','Flowery Branch','Braselton','Lula','Clermont'],
    Chatham: ['Savannah','Garden City','Pooler','Port Wentworth','Thunderbolt','Tybee Island'],
    Bibb: ['Macon','Warner Robins','Centerville','Bonaire','Byron'],
    Houston: ['Warner Robins','Perry','Centerville','Bonaire','Byron'],
    Muscogee: ['Columbus','Midland','Upatoi'],
    Lowndes: ['Valdosta','Hahira','Lake Park','Dasher','Clyattville'],
  },
  HI: {
    Honolulu: ['Honolulu','Pearl City','Kailua','Kaneohe','Waipahu','Mililani','Ewa Beach'],
    Hawaii: ['Hilo','Kailua-Kona','Waimea','Pahoa','Captain Cook'],
    Maui: ['Kahului','Wailuku','Kihei','Lahaina','Makawao','Kula'],
    Kauai: ['Lihue','Kapaa','Poipu','Princeville','Waimea','Hanapepe'],
  },
  ID: {
    Ada: ['Boise','Meridian','Eagle','Kuna','Garden City','Star'],
    Canyon: ['Nampa','Caldwell','Middleton','Notus','Parma','Wilder'],
    Kootenai: ['Coeur d\'Alene','Post Falls','Hayden','Rathdrum','Spirit Lake'],
    'Twin Falls': ['Twin Falls','Kimberly','Filer','Buhl','Jerome','Eden'],
    Bannock: ['Pocatello','Chubbuck','Inkom','McCammon','Lava Hot Springs'],
    Bonneville: ['Idaho Falls','Ammon','Ucon','Iona','Rigby','Shelley'],
  },
  IL: {
    Cook: ['Chicago','Evanston','Skokie','Oak Park','Cicero','Berwyn','Arlington Heights','Naperville','Waukegan','Des Plaines','Schaumburg','Elgin'],
    DuPage: ['Aurora','Naperville','Bolingbrook','Wheaton','Downers Grove','Elmhurst','Villa Park','Lombard'],
    Lake: ['Waukegan','North Chicago','Gurnee','Vernon Hills','Buffalo Grove','Mundelein','Lake Forest'],
    Will: ['Joliet','Romeoville','Bolingbrook','Plainfield','New Lenox','Lockport','Crest Hill'],
    Kane: ['Aurora','Elgin','Batavia','Geneva','St. Charles','North Aurora'],
    McHenry: ['Crystal Lake','McHenry','Woodstock','Algonquin','Huntley','Cary'],
    Winnebago: ['Rockford','Loves Park','Machesney Park','Roscoe','Cherry Valley'],
    Madison: ['Alton','Edwardsville','Granite City','Collinsville','Troy','Maryville','Highland'],
    'St. Clair': ['O\'Fallon','Belleville','Shiloh','Swansea','Mascoutah','Fairview Heights'],
    Champaign: ['Champaign','Urbana','Rantoul','Savoy','Mahomet','Tolono'],
    Sangamon: ['Springfield','Chatham','Rochester','Sherman','Riverton','Williamsville'],
  },
  IN: {
    Marion: ['Indianapolis','Lawrence','Beech Grove','Speedway','Southport'],
    Lake: ['Gary','Hammond','Merrillville','Munster','Highland','Crown Point','Valparaiso'],
    Allen: ['Fort Wayne','New Haven','Woodburn','Leo-Cedarville','Huntertown'],
    Hamilton: ['Fishers','Carmel','Noblesville','Westfield','Cicero','Sheridan'],
    'St. Joseph': ['South Bend','Mishawaka','Granger','Osceola','Lakeville'],
    Tippecanoe: ['Lafayette','West Lafayette','Battle Ground','Dayton','Shadeland'],
    Elkhart: ['Elkhart','Goshen','Nappanee','Middlebury','Bristol','Wakarusa'],
    Vanderburgh: ['Evansville','Newburgh','Chandler','Boonville','Darmstadt'],
    Monroe: ['Bloomington','Ellettsville','Stinesville','Harrodsburg','Unionville'],
  },
  IA: {
    Polk: ['Des Moines','Ankeny','West Des Moines','Urbandale','Johnston','Clive','Pleasant Hill'],
    Linn: ['Cedar Rapids','Marion','Hiawatha','Robins','Mount Vernon','Fairfax'],
    Scott: ['Davenport','Bettendorf','Eldridge','LeClaire','Buffalo'],
    Johnson: ['Iowa City','Coralville','North Liberty','University Heights','Hills'],
    'Black Hawk': ['Waterloo','Cedar Falls','Evansdale','Hudson','Elk Run Heights'],
    Woodbury: ['Sioux City','South Sioux City','North Sioux City','Dakota City','Sergeant Bluff'],
    Story: ['Ames','Nevada','Gilbert','Roland','Slater','Huxley'],
    Dallas: ['Adel','Waukee','Grimes','Dallas Center','Perry','De Soto'],
  },
  KS: {
    Johnson: ['Overland Park','Olathe','Lenexa','Shawnee','Leawood','Merriam','Prairie Village','Mission'],
    Sedgwick: ['Wichita','Derby','Haysville','Andover','Valley Center','Cheney'],
    Shawnee: ['Topeka','Auburn','Silver Lake','Rossville','Willard'],
    Wyandotte: ['Kansas City','Bonner Springs','Edwardsville','Lake Quivira','Basehor'],
    Douglas: ['Lawrence','Eudora','Baldwin City','Lecompton','Lone Star'],
    Riley: ['Manhattan','Junction City','Ogden','Riley','Wamego'],
  },
  KY: {
    Jefferson: ['Louisville','Jeffersontown','Shively','St. Matthews','Middletown','Lyndon'],
    Fayette: ['Lexington','Nicholasville','Versailles','Georgetown','Winchester'],
    Kenton: ['Covington','Newport','Florence','Edgewood','Erlanger','Independence'],
    Boone: ['Florence','Union','Erlanger','Burlington','Petersburg','Walton'],
    Warren: ['Bowling Green','Smiths Grove','Scottsville','Oakland','Riverside'],
    Campbell: ['Newport','Alexandria','Cold Spring','Fort Thomas','Bellevue','Dayton'],
    Hardin: ['Elizabethtown','Radcliff','Vine Grove','Rineyville','Cecilia'],
    Madison: ['Richmond','Berea','Waco','Kirksville','Paint Lick'],
  },
  LA: {
    'East Baton Rouge': ['Baton Rouge','Zachary','Baker','Central','Denham Springs'],
    Jefferson: ['Metairie','Kenner','Gretna','Westwood','Marrero','Harvey','Terrytown'],
    Orleans: ['New Orleans'],
    'St. Tammany': ['Slidell','Covington','Mandeville','Bogalusa','Pearl River','Abita Springs'],
    Caddo: ['Shreveport','Bossier City','Vivian','Greenwood','Oil City'],
    Calcasieu: ['Lake Charles','Westlake','Sulphur','Vinton','Moss Bluff','Iowa'],
    Lafayette: ['Lafayette','Broussard','Youngsville','Scott','Carencro','Duson'],
    Rapides: ['Alexandria','Pineville','Ball','Woodworth','Lecompte','Cheneyville'],
  },
  ME: {
    Cumberland: ['Portland','South Portland','Westbrook','Gorham','Scarborough','Cape Elizabeth','Falmouth'],
    York: ['Saco','Biddeford','Sanford','Kennebunk','York','Wells','Kittery','South Berwick'],
    Penobscot: ['Bangor','Brewer','Old Town','Orono','Lincoln','Hampden'],
    Kennebec: ['Augusta','Waterville','Winthrop','Gardiner','Hallowell','Oakland'],
    Androscoggin: ['Lewiston','Auburn','Lisbon','Lisbon Falls','Greene','Poland'],
  },
  MD: {
    Montgomery: ['Rockville','Gaithersburg','Silver Spring','Bethesda','Germantown','Wheaton','Aspen Hill'],
    'Prince George\'s': ['Bowie','Laurel','College Park','Greenbelt','Hyattsville','Largo','Landover'],
    Baltimore: ['Towson','Dundalk','Parkville','Catonsville','Essex','Middle River','Rosedale'],
    'Anne Arundel': ['Annapolis','Glen Burnie','Laurel','Bowie','Odenton','Severn','Severna Park'],
    Howard: ['Columbia','Ellicott City','Jessup','Clarksville','Fulton','Glenelg'],
    Frederick: ['Frederick','Hagerstown','Thurmont','Brunswick','Middletown','Walkersville'],
    Charles: ['Waldorf','La Plata','Indian Head','White Plains','St. Charles','Bryans Road'],
    Harford: ['Bel Air','Aberdeen','Havre de Grace','Edgewood','Joppatowne','Fallston'],
  },
  MA: {
    Middlesex: ['Cambridge','Lowell','Newton','Somerville','Waltham','Framingham','Malden','Medford','Woburn','Watertown'],
    Worcester: ['Worcester','Fitchburg','Gardner','Leominster','Shrewsbury','Milford','Southbridge'],
    Essex: ['Salem','Lynn','Haverhill','Methuen','Lawrence','Peabody','Beverly','Gloucester'],
    Suffolk: ['Boston','Chelsea','Revere','Winthrop'],
    Norfolk: ['Quincy','Braintree','Weymouth','Needham','Dedham','Milton','Stoughton','Canton'],
    Bristol: ['New Bedford','Fall River','Taunton','Attleboro','Brockton','Easton','Mansfield'],
    Plymouth: ['Brockton','Plymouth','Bridgewater','Middleborough','Carver','Kingston'],
    Hampden: ['Springfield','Chicopee','Holyoke','Westfield','West Springfield','Agawam'],
  },
  MI: {
    Wayne: ['Detroit','Dearborn','Westland','Livonia','Warren','Lincoln Park','Dearborn Heights','Taylor'],
    Oakland: ['Troy','Southfield','Pontiac','Royal Oak','Farmington Hills','Auburn Hills','Rochester Hills','Sterling Heights'],
    Macomb: ['Sterling Heights','Warren','Clinton Township','St. Clair Shores','Roseville','Utica'],
    Kent: ['Grand Rapids','Wyoming','Kentwood','Walker','Grandville','East Grand Rapids'],
    Genesee: ['Flint','Burton','Flint Township','Grand Blanc','Flushing','Clio'],
    Washtenaw: ['Ann Arbor','Ypsilanti','Saline','Chelsea','Dexter','Milan'],
    Ingham: ['Lansing','East Lansing','Meridian','Mason','Okemos','Haslett'],
    Kalamazoo: ['Kalamazoo','Portage','Comstock','Oshtemo','Texas Township','Galesburg'],
    Ottawa: ['Holland','Grand Haven','Zeeland','Jenison','Hudsonville','Allendale'],
  },
  MN: {
    Hennepin: ['Minneapolis','Brooklyn Park','Plymouth','Bloomington','Eden Prairie','Minnetonka','Edina','St. Louis Park','Burnsville'],
    Ramsey: ['St. Paul','Roseville','Maplewood','Shoreview','New Brighton','Arden Hills'],
    Dakota: ['Burnsville','Eagan','Apple Valley','Lakeville','Inver Grove Heights','Farmington'],
    Anoka: ['Coon Rapids','Blaine','Anoka','Brooklyn Park','Fridley','Spring Lake Park'],
    Washington: ['Woodbury','Cottage Grove','Stillwater','Oakdale','Forest Lake','Hugo','Mahtomedi'],
    Scott: ['Shakopee','Prior Lake','Savage','Jordan','Belle Plaine','New Prague'],
    Sherburne: ['Elk River','Becker','Big Lake','Zimmerman','Monticello','Princeton'],
    Wright: ['Buffalo','Monticello','St. Michael','Delano','Howard Lake','Maple Lake'],
    Olmsted: ['Rochester','Byron','Stewartville','Kasson','Dodge Center','Chatfield'],
  },
  MS: {
    Hinds: ['Jackson','Clinton','Byram','Ridgeland','Flowood','Raymond'],
    Harrison: ['Gulfport','Biloxi','D\'Iberville','Long Beach','Pass Christian','Ocean Springs'],
    DeSoto: ['Southaven','Horn Lake','Hernando','Olive Branch','Walls','Coldwater'],
    Madison: ['Madison','Ridgeland','Flora','Gluckstadt','Camden'],
    Rankin: ['Pearl','Brandon','Flowood','Richland','Florence','Pelahatchie'],
    Forrest: ['Hattiesburg','Petal','Purvis','Lumberton','Oak Grove'],
    Jackson: ['Pascagoula','Gautier','Ocean Springs','Moss Point','Escatawpa','Leakesville'],
    Lee: ['Tupelo','Baldwyn','Guntown','Booneville','Sherman','Verona'],
  },
  MO: {
    'St. Louis': ['Chesterfield','Florissant','Kirkwood','St. Peters','Clayton','Ballwin'],
    Jackson: ['Kansas City','Independence','Lee\'s Summit','Blue Springs','Raytown','Grandview'],
    'St. Charles': ['St. Charles','O\'Fallon','St. Peters','Wentzville','Lake St. Louis','Cottleville'],
    Greene: ['Springfield','Republic','Nixa','Battlefield','Willard','Ozark'],
    Jefferson: ['Festus','Crystal City','Arnold','Hillsboro','Imperial','De Soto'],
    Clay: ['Liberty','Kearney','Excelsior Springs','North Kansas City','Gladstone','Smithville'],
    Boone: ['Columbia','Centralia','Ashland','Hallsville','Rocheport','Sturgeon'],
    Franklin: ['Union','Washington','Sullivan','Pacific','St. Clair','Owensville'],
  },
  MT: {
    Yellowstone: ['Billings','Lockwood','Laurel','Broadview','Columbus'],
    Cascade: ['Great Falls','Black Eagle','Belt','Cascade','Simms'],
    Missoula: ['Missoula','Lolo','Frenchtown','Clinton','Seeley Lake'],
    Gallatin: ['Bozeman','Belgrade','Manhattan','Three Forks','West Yellowstone'],
    Lake: ['Polson','Ronan','St. Ignatius','Pablo','Arlee'],
    Flathead: ['Kalispell','Whitefish','Columbia Falls','Bigfork','Lakeside','Marion'],
    Ravalli: ['Hamilton','Stevensville','Victor','Corvallis','Florence'],
    'Lewis and Clark': ['Helena','East Helena','Boulder','Lincoln','Wolf Creek'],
  },
  NE: {
    Douglas: ['Omaha','Bellevue','Papillion','La Vista','Ralston','Valley'],
    Lancaster: ['Lincoln','Waverly','Hickman','Raymond','Emerald','Bennet'],
    Sarpy: ['Bellevue','Papillion','La Vista','Gretna','Springfield','Plattsmouth'],
    Hall: ['Grand Island','Wood River','Alda','Cairo','Doniphan','Hastings'],
    Buffalo: ['Kearney','Gibbon','Shelton','Ravenna','Elm Creek'],
    Platte: ['Columbus','Humphrey','Schuyler','Clarkson','Leigh'],
  },
  NV: {
    Clark: ['Las Vegas','Henderson','North Las Vegas','Enterprise','Sunrise Manor','Spring Valley','Paradise','Summerlin South'],
    Washoe: ['Reno','Sparks','Sun Valley','Spanish Springs','Cold Springs'],
    'Carson City': ['Carson City'],
    Elko: ['Elko','Spring Creek','Carlin','Wells','West Wendover'],
    Douglas: ['Gardnerville','Minden','Stateline','Genoa','Topaz Ranch Estates'],
    Lyon: ['Yerington','Fernley','Dayton','Silver Springs','Smith Valley'],
  },
  NH: {
    Hillsborough: ['Manchester','Nashua','Milford','Merrimack','Bedford','Londonderry','Hudson','Amherst'],
    Rockingham: ['Derry','Portsmouth','Salem','Exeter','Hampton','Windham','Plaistow','Auburn'],
    Merrimack: ['Concord','Laconia','Franklin','Bow','Pembroke','Hooksett','Hopkinton'],
    Strafford: ['Dover','Rochester','Somersworth','Durham','Barrington','Madbury'],
    Cheshire: ['Keene','Swanzey','Cheshire','Winchester','Hinsdale','Walpole'],
  },
  NJ: {
    Bergen: ['Hackensack','Paramus','Fort Lee','Englewood','Teaneck','Fair Lawn','Garfield','Clifton'],
    Middlesex: ['New Brunswick','Edison','Woodbridge','Piscataway','East Brunswick','Old Bridge','Sayreville'],
    Essex: ['Newark','Irvington','East Orange','Orange','Livingston','Bloomfield','Montclair','Nutley'],
    Hudson: ['Jersey City','Bayonne','Union City','West New York','Hoboken','Kearny','North Bergen'],
    Monmouth: ['Asbury Park','Long Branch','Red Bank','Freehold','Middletown','Tinton Falls','Brick'],
    Union: ['Elizabeth','Union','Plainfield','Scotch Plains','Westfield','Linden','Rahway','Roselle'],
    Ocean: ['Toms River','Lakewood','Manchester','Jackson','Brick','Barnegat','Berkeley'],
    Morris: ['Morristown','Parsippany','Rockaway','Dover','Randolph','Denville','Mount Olive'],
    Camden: ['Camden','Cherry Hill','Gloucester Township','Winslow','Hamilton','Voorhees'],
  },
  NM: {
    Bernalillo: ['Albuquerque','Rio Rancho','Tijeras','Los Ranchos','South Valley','Corrales'],
    'Dona Ana': ['Las Cruces','Sunland Park','Anthony','Chaparral','Hatch','Mesilla'],
    'Santa Fe': ['Santa Fe','Española','Pojoaque','El Rancho','Chimayó'],
    Sandoval: ['Rio Rancho','Bernalillo','Corrales','Placitas','Cuba'],
    'San Juan': ['Farmington','Aztec','Bloomfield','Flora Vista','Cedar Hill'],
    Otero: ['Alamogordo','Cloudcroft','Tularosa','Chaparral','Bent'],
  },
  NY: {
    Kings: ['Brooklyn'],
    Queens: ['Flushing','Jamaica','Astoria','Jackson Heights','Corona','Forest Hills','Ridgewood'],
    'New York': ['Manhattan'],
    Suffolk: ['Islip','Brookhaven','Babylon','Huntington','Smithtown','Southampton','East Hampton'],
    Bronx: ['The Bronx'],
    Nassau: ['Hempstead','Long Beach','Glen Cove','Great Neck','Mineola','Garden City','Freeport'],
    Westchester: ['Yonkers','New Rochelle','Mount Vernon','White Plains','Greenburgh','Peekskill','Rye'],
    Erie: ['Buffalo','Cheektowaga','Tonawanda','Amherst','Niagara Falls','Lackawanna','Lancaster'],
    Monroe: ['Rochester','Greece','Irondequoit','Penfield','Webster','Brighton','Gates'],
    Onondaga: ['Syracuse','Salina','DeWitt','Clay','Geddes','Onondaga','Manlius'],
    Albany: ['Albany','Colonie','Bethlehem','Guilderland','Green Island','Watervliet','Cohoes'],
    Dutchess: ['Poughkeepsie','Fishkill','Wappingers Falls','Beacon','LaGrange','Hyde Park'],
  },
  NC: {
    Mecklenburg: ['Charlotte','Pineville','Matthews','Mint Hill','Huntersville','Cornelius','Davidson','Mooresville'],
    Wake: ['Raleigh','Cary','Apex','Holly Springs','Fuquay-Varina','Morrisville','Wake Forest','Garner'],
    Guilford: ['Greensboro','High Point','Jamestown','Whitsett','Gibsonville'],
    Forsyth: ['Winston-Salem','Kernersville','Lewisville','Clemmons','Rural Hall'],
    Cumberland: ['Fayetteville','Spring Lake','Hope Mills','Eastover','Stedman'],
    Durham: ['Durham','Bethel','Bahama'],
    Buncombe: ['Asheville','Woodfin','Weaverville','Swannanoa','Black Mountain','Biltmore Forest'],
    Union: ['Monroe','Waxhaw','Indian Trail','Matthews','Stallings','Marvin','Wesley Chapel'],
    Cabarrus: ['Concord','Kannapolis','Harrisburg','Midland','Mount Pleasant'],
    Onslow: ['Jacksonville','Swansboro','Camp Lejeune','Sneads Ferry','Richlands'],
    Gaston: ['Gastonia','Belmont','Bessemer City','Kings Mountain','Cramerton','Mount Holly'],
    'New Hanover': ['Wilmington','Leland','Wrightsville Beach','Carolina Beach','Kure Beach','Porters Neck'],
  },
  ND: {
    Cass: ['Fargo','West Fargo','Moorhead','Horace','Casselton','Kindred'],
    Burleigh: ['Bismarck','Lincoln','Wilton','Menoken','Regan'],
    'Grand Forks': ['Grand Forks','East Grand Forks','Emerado','Larimore','Thompson'],
    Ward: ['Minot','Burlington','Surrey','Sawyer','Velva'],
    Morton: ['Mandan','New Salem','Flasher','Glen Ullin','Hebron'],
    Williams: ['Williston','Tioga','Ray','Grenora','Wildrose'],
  },
  OH: {
    Franklin: ['Columbus','Dublin','Westerville','Hilliard','Gahanna','Grove City','Reynoldsburg','Upper Arlington','Whitehall'],
    Cuyahoga: ['Cleveland','Cleveland Heights','Lakewood','Parma','Euclid','Strongsville','North Olmsted','Middleburg Heights'],
    Hamilton: ['Cincinnati','Norwood','Forest Park','Blue Ash','Fairfield','Mason','Loveland'],
    Summit: ['Akron','Cuyahoga Falls','Stow','Tallmadge','Barberton','Hudson','Twinsburg'],
    Montgomery: ['Dayton','Kettering','Huber Heights','Beavercreek','Fairborn','Trotwood','Miamisburg'],
    Lucas: ['Toledo','Maumee','Sylvania','Oregon','Perrysburg','Waterville','Monclova'],
    Butler: ['Hamilton','Middletown','Fairfield','West Chester','Monroe','Oxford','Trenton'],
    Stark: ['Canton','Massillon','North Canton','Louisville','Perry Township','Belden','Jackson Township'],
    Lorain: ['Lorain','Elyria','Amherst','Avon','Avon Lake','Sheffield Lake','Oberlin'],
    Delaware: ['Delaware','Powell','Westerville','Lewis Center','Dublin','Sunbury'],
    Clark: ['Springfield','Enon','South Charleston','New Carlisle','Urbana','Tipp City'],
  },
  OK: {
    Oklahoma: ['Oklahoma City','Edmond','Midwest City','Moore','Norman','Del City','Yukon','Mustang'],
    Tulsa: ['Tulsa','Broken Arrow','Owasso','Jenks','Bixby','Sand Springs','Sapulpa'],
    Cleveland: ['Norman','Moore','Midwest City','Little Axe','Slaughterville'],
    Canadian: ['Yukon','Mustang','El Reno','Weatherford','Chickasha'],
    Comanche: ['Lawton','Cache','Elgin','Fletcher','Comanche'],
    Wagoner: ['Wagoner','Coweta','Broken Arrow','Claremore','Catoosa'],
    Rogers: ['Claremore','Catoosa','Inola','Verdigris','Chelsea'],
  },
  OR: {
    Multnomah: ['Portland','Gresham','Troutdale','Fairview','Wood Village','Maywood Park'],
    Washington: ['Beaverton','Hillsboro','Tigard','Lake Oswego','Tualatin','Sherwood','Newberg'],
    Clackamas: ['Lake Oswego','Milwaukie','Happy Valley','West Linn','Oregon City','Canby','Wilsonville'],
    Lane: ['Eugene','Springfield','Cottage Grove','Junction City','Florence','Creswell'],
    Marion: ['Salem','Keizer','Woodburn','Silverton','Stayton','Turner'],
    Jackson: ['Medford','Ashland','Jacksonville','Grants Pass','Central Point','Eagle Point'],
    Deschutes: ['Bend','Redmond','Sisters','La Pine','Sunriver'],
    Yamhill: ['McMinnville','Newberg','Sheridan','Amity','Dayton','Carlton'],
    Benton: ['Corvallis','Philomath','Adair Village','Monroe','Alsea'],
    Josephine: ['Grants Pass','Cave Junction','Kerby','Wolf Creek','Selma'],
  },
  PA: {
    Philadelphia: ['Philadelphia'],
    Allegheny: ['Pittsburgh','McKeesport','Bethel Park','Mount Lebanon','Monroeville','Plum','Penn Hills'],
    Montgomery: ['Norristown','King of Prussia','Lansdale','Pottstown','Horsham','Abington','Plymouth Meeting'],
    Bucks: ['Levittown','Bristol','Doylestown','Newtown','Warminster','Horsham','Langhorne'],
    Delaware: ['Chester','Upper Darby','Haverford','Marple','Springfield','Ridley','Radnor'],
    Chester: ['West Chester','Coatesville','Phoenixville','Downingtown','Malvern','Kennett Square'],
    Lancaster: ['Lancaster','Ephrata','Lititz','Manheim','Elizabethtown','Columbia','Mountville'],
    York: ['York','Hanover','Dallastown','Red Lion','Spring Grove','Dover'],
    Luzerne: ['Wilkes-Barre','Scranton','Hazleton','Kingston','Pittston','Nanticoke','Plains'],
    Berks: ['Reading','Wyomissing','Kutztown','Boyertown','Exeter','Shillington','Muhlenberg'],
    Westmoreland: ['Greensburg','Jeannette','Murrysville','Lower Burrell','New Kensington','Arnold'],
  },
  RI: {
    Providence: ['Providence','Cranston','Pawtucket','North Providence','Johnston','Lincoln','North Smithfield'],
    Kent: ['Warwick','West Warwick','Coventry','East Greenwich','West Greenwich'],
    Washington: ['South Kingstown','Narragansett','Westerly','Hopkinton','Charlestown','Richmond'],
    Newport: ['Newport','Middletown','Portsmouth','Tiverton','Little Compton','Jamestown'],
    Bristol: ['Bristol','Barrington','Warren'],
  },
  SC: {
    Greenville: ['Greenville','Greer','Mauldin','Simpsonville','Taylors','Fountain Inn','Travelers Rest'],
    Richland: ['Columbia','Forest Acres','Cayce','Blythewood','Chapin'],
    Charleston: ['Charleston','North Charleston','Mount Pleasant','Summerville','Goose Creek','James Island','Hanahan'],
    Horry: ['Myrtle Beach','Conway','North Myrtle Beach','Surfside Beach','Socastee','Little River'],
    Spartanburg: ['Spartanburg','Duncan','Greer','Boiling Springs','Inman','Gaffney','Cowpens'],
    Anderson: ['Anderson','Belton','Williamston','Iva','Powdersville','Pendleton'],
    Lexington: ['Lexington','Cayce','West Columbia','Chapin','Irmo','Swansea','Batesburg-Leesville'],
    Beaufort: ['Beaufort','Bluffton','Hilton Head Island','Port Royal','Ridgeland','Hardeeville'],
    York: ['Rock Hill','Fort Mill','Clover','York','Lake Wylie','Tega Cay','Catawba'],
  },
  SD: {
    Minnehaha: ['Sioux Falls','Brandon','Valley Springs','Baltic','Hartford'],
    Pennington: ['Rapid City','Box Elder','Summerset','Piedmont','Blackhawk'],
    Lincoln: ['Tea','Harrisburg','Canton','Lennox','Worthing','Sioux Falls'],
    Brown: ['Aberdeen','Groton','Columbia','Bath','Warner'],
    Codington: ['Watertown','Henry','Florence','Castlewood'],
    Brookings: ['Brookings','Volga','Aurora','White','Sinai'],
  },
  TN: {
    Shelby: ['Memphis','Germantown','Collierville','Bartlett','Cordova','Millington','Arlington'],
    Davidson: ['Nashville','Brentwood','Franklin','Antioch','Nolensville'],
    Knox: ['Knoxville','Farragut','Powell','Halls','Corryton','Hardin Valley'],
    Hamilton: ['Chattanooga','East Ridge','Red Bank','Soddy-Daisy','Signal Mountain','Collegedale'],
    Williamson: ['Franklin','Brentwood','Spring Hill','Nolensville','Thompson\'s Station','Fairview'],
    Rutherford: ['Murfreesboro','Smyrna','LaVergne','Rockvale','Lascassas','Eagleville'],
    Montgomery: ['Clarksville','Oak Grove','Hopkinsville','St. Bethlehem','Palmyra'],
    Sumner: ['Hendersonville','Gallatin','Goodlettsville','White House','Portland','Millersville'],
    Blount: ['Maryville','Alcoa','Friendsville','Louisville','Townsend','Walland'],
    Madison: ['Jackson','Humboldt','Medina','Denmark','Oakfield'],
  },
  TX: {
    Harris: ['Houston','Pasadena','Baytown','Katy','Sugar Land','Missouri City','League City','Pearland','Spring','Humble','Conroe'],
    Dallas: ['Dallas','Irving','Garland','Plano','Mesquite','Carrollton','Richardson','Grand Prairie','Rowlett','Balch Springs'],
    Tarrant: ['Fort Worth','Arlington','Grand Prairie','Mansfield','North Richland Hills','Euless','Bedford','Hurst','Keller','Grapevine','Southlake','Colleyville'],
    Bexar: ['San Antonio','Leon Valley','Converse','Universal City','Live Oak','Schertz','Helotes','Kirby'],
    Travis: ['Austin','Round Rock','Cedar Park','Georgetown','Pflugerville','Manor','Lakeway','Bee Cave'],
    Collin: ['Plano','McKinney','Frisco','Allen','Wylie','Murphy','Sachse','Prosper','Celina'],
    Hidalgo: ['McAllen','Edinburg','Mission','Pharr','Weslaco','Harlingen','Mercedes','Donna'],
    'El Paso': ['El Paso','Socorro','Anthony','Canutillo','Horizon City','San Elizario'],
    Denton: ['Denton','Lewisville','Flower Mound','The Colony','Corinth','Argyle','Little Elm'],
    'Fort Bend': ['Sugar Land','Missouri City','Pearland','Richmond','Rosenberg','Stafford','Katy','Fulshear'],
    Williamson: ['Round Rock','Georgetown','Cedar Park','Pflugerville','Taylor','Hutto','Leander','Liberty Hill'],
    Montgomery: ['Conroe','The Woodlands','Spring','Humble','Magnolia','Willis','Tomball'],
    Nueces: ['Corpus Christi','Portland','Robstown','Calallen','Agua Dulce'],
    Bell: ['Killeen','Temple','Belton','Waco','Hewitt','Lorena','Nolanville'],
    Galveston: ['Galveston','Texas City','League City','La Marque','Dickinson','Friendswood','Webster'],
    Lubbock: ['Lubbock','Slaton','Wolfforth','Shallowater','Idalou','Ransom Canyon'],
    Hays: ['San Marcos','Kyle','Buda','Wimberley','Dripping Springs','Niederwald'],
    McLennan: ['Waco','Hewitt','Woodway','Bellmead','Lacy-Lakeview','Lorena'],
  },
  UT: {
    'Salt Lake': ['Salt Lake City','West Valley City','West Jordan','Sandy','Millcreek','South Jordan','Murray','Taylorsville','Midvale','Draper','Cottonwood Heights'],
    Utah: ['Provo','Orem','Lehi','American Fork','Spanish Fork','Springville','Payson','Saratoga Springs'],
    Davis: ['Layton','Bountiful','Kaysville','Clearfield','Clinton','Syracuse','Centerville','Farmington'],
    Weber: ['Ogden','Roy','South Ogden','Riverdale','Washington Terrace','Harrisville'],
    Washington: ['St. George','Washington','Hurricane','Ivins','Santa Clara','La Verkin'],
    Cache: ['Logan','North Logan','Providence','Smithfield','Hyrum','Millville'],
    Iron: ['Cedar City','Enoch','Parowan','Paragonah','Summit'],
    Tooele: ['Tooele','Grantsville','Stansbury Park','Erda','Vernon'],
  },
  VT: {
    Chittenden: ['Burlington','South Burlington','Williston','Shelburne','Essex','Colchester','Winooski','Milton'],
    Rutland: ['Rutland','Castleton','Poultney','Pittsford','Killington','Proctor'],
    Washington: ['Montpelier','Barre','Northfield','Berlin','Waitsfield','Warren'],
    Windsor: ['Springfield','Windsor','Woodstock','Hartford','Hartland','Sharon'],
    Franklin: ['St. Albans','Swanton','Sheldon','Enosburg Falls','Montgomery'],
    Addison: ['Middlebury','Vergennes','Bristol','Weybridge','Bridport'],
  },
  VA: {
    Fairfax: ['Fairfax','Reston','Herndon','McLean','Vienna','Annandale','Springfield','Centreville','Chantilly'],
    'Prince William': ['Manassas','Woodbridge','Dale City','Gainesville','Lake Ridge','Dumfries','Bristow'],
    Loudoun: ['Leesburg','Ashburn','Sterling','Dulles','Broadlands','Lansdowne','Purcellville'],
    Chesterfield: ['Chesterfield','Midlothian','Chester','Bon Air','Colonial Heights'],
    Arlington: ['Arlington','Ballston','Clarendon','Rosslyn','Pentagon City'],
    Henrico: ['Richmond','Glen Allen','Sandston','Short Pump','Lakeside'],
    Spotsylvania: ['Fredericksburg','Spotsylvania','Massaponax','Chancellor','Thornburg'],
    Stafford: ['Stafford','Falmouth','Aquia Harbour','Garrisonville','Widewater'],
    Montgomery: ['Blacksburg','Christiansburg','Radford','Shawsville','Elliston'],
    Augusta: ['Waynesboro','Staunton','Fishersville','Verona','Crimora'],
  },
  WA: {
    King: ['Seattle','Bellevue','Kent','Renton','Federal Way','Kirkland','Redmond','Sammamish','Shoreline','Burien','Auburn','Bothell'],
    Pierce: ['Tacoma','Lakewood','Federal Way','Puyallup','Renton','Bonney Lake','Gig Harbor','Sumner','Milton','Edgewood'],
    Snohomish: ['Everett','Marysville','Lynnwood','Edmonds','Mountlake Terrace','Bothell','Mukilteo','Mill Creek'],
    Spokane: ['Spokane','Spokane Valley','Cheney','Medical Lake','Liberty Lake','Airway Heights'],
    Clark: ['Vancouver','Camas','Washougal','Battle Ground','Ridgefield','La Center'],
    Thurston: ['Olympia','Lacey','Tumwater','Rainier','Yelm','Bucoda'],
    Kitsap: ['Bremerton','Poulsbo','Port Orchard','Silverdale','Kingston','Bainbridge Island'],
    Whatcom: ['Bellingham','Lynden','Blaine','Ferndale','Sumas','Nooksack'],
    Yakima: ['Yakima','Selah','Union Gap','Moxee','Terrace Heights','West Valley'],
  },
  WV: {
    Kanawha: ['Charleston','South Charleston','St. Albans','Dunbar','Nitro','Hurricane','Cross Lanes'],
    Cabell: ['Huntington','Barboursville','Milton','Kenova','Ceredo'],
    Wood: ['Parkersburg','Vienna','Williamstown','Belpre'],
    Berkeley: ['Martinsburg','Inwood','Hedgesville','Bunker Hill','Falling Waters'],
    Monongalia: ['Morgantown','Westover','Star City','Granville','Cheat Lake'],
    Raleigh: ['Beckley','Sophia','Beaver','Daniels','Cool Ridge','Ghent'],
    Putnam: ['Hurricane','Teays Valley','Scott Depot','Winfield','Eleanor','Buffalo'],
    Mercer: ['Princeton','Bluefield','Athens','Oakvale','Bramwell','Matoaka'],
  },
  WI: {
    Milwaukee: ['Milwaukee','Wauwatosa','West Allis','Greenfield','Oak Creek','South Milwaukee','Greendale'],
    Dane: ['Madison','Sun Prairie','Middleton','Fitchburg','Monona','Verona','Stoughton','DeForest'],
    Waukesha: ['Waukesha','Brookfield','New Berlin','Muskego','Oconomowoc','Pewaukee','Sussex','Menomonee Falls'],
    Brown: ['Green Bay','De Pere','Allouez','Ashwaubenon','Bellevue','Howard','Pulaski'],
    Racine: ['Racine','Mount Pleasant','Caledonia','Burlington','Wind Point','Elmwood Park'],
    Outagamie: ['Appleton','Kaukauna','Kimberly','Little Chute','Combined Locks','Seymour'],
    Winnebago: ['Oshkosh','Neenah','Menasha','Omro','Winneconne','Butte des Morts'],
    Rock: ['Janesville','Beloit','Evansville','Milton','Edgerton','Clinton'],
    Kenosha: ['Kenosha','Pleasant Prairie','Bristol','Somers','Paddock Lake','Twin Lakes'],
    Marathon: ['Wausau','Schofield','Rothschild','Rib Mountain','Weston','Kronenwetter'],
  },
  WY: {
    Laramie: ['Cheyenne','Burns','Pine Bluffs','Albin','Hillsdale'],
    Natrona: ['Casper','Mills','Evansville','Bar Nunn','Midwest'],
    Campbell: ['Gillette','Wright','Recluse'],
    Sweetwater: ['Rock Springs','Green River','Reliance','Point of Rocks'],
    Fremont: ['Lander','Riverton','Dubois','Hudson','Shoshoni'],
    Teton: ['Jackson','Wilson','Teton Village','Alta'],
    Albany: ['Laramie','Rock River','Centennial','Bosler','Garrett'],
    Sheridan: ['Sheridan','Ranchester','Clearmont','Dayton','Story'],
  },
}
