export const STATES: { code: string; name: string }[] = [
  { code: 'AL', name: 'Alabama' },
  { code: 'AK', name: 'Alaska' },
  { code: 'AZ', name: 'Arizona' },
  { code: 'AR', name: 'Arkansas' },
  { code: 'CA', name: 'California' },
  { code: 'CO', name: 'Colorado' },
  { code: 'CT', name: 'Connecticut' },
  { code: 'DE', name: 'Delaware' },
  { code: 'FL', name: 'Florida' },
  { code: 'GA', name: 'Georgia' },
  { code: 'HI', name: 'Hawaii' },
  { code: 'ID', name: 'Idaho' },
  { code: 'IL', name: 'Illinois' },
  { code: 'IN', name: 'Indiana' },
  { code: 'IA', name: 'Iowa' },
  { code: 'KS', name: 'Kansas' },
  { code: 'KY', name: 'Kentucky' },
  { code: 'LA', name: 'Louisiana' },
  { code: 'ME', name: 'Maine' },
  { code: 'MD', name: 'Maryland' },
  { code: 'MA', name: 'Massachusetts' },
  { code: 'MI', name: 'Michigan' },
  { code: 'MN', name: 'Minnesota' },
  { code: 'MS', name: 'Mississippi' },
  { code: 'MO', name: 'Missouri' },
  { code: 'MT', name: 'Montana' },
  { code: 'NE', name: 'Nebraska' },
  { code: 'NV', name: 'Nevada' },
  { code: 'NH', name: 'New Hampshire' },
  { code: 'NJ', name: 'New Jersey' },
  { code: 'NM', name: 'New Mexico' },
  { code: 'NY', name: 'New York' },
  { code: 'NC', name: 'North Carolina' },
  { code: 'ND', name: 'North Dakota' },
  { code: 'OH', name: 'Ohio' },
  { code: 'OK', name: 'Oklahoma' },
  { code: 'OR', name: 'Oregon' },
  { code: 'PA', name: 'Pennsylvania' },
  { code: 'RI', name: 'Rhode Island' },
  { code: 'SC', name: 'South Carolina' },
  { code: 'SD', name: 'South Dakota' },
  { code: 'TN', name: 'Tennessee' },
  { code: 'TX', name: 'Texas' },
  { code: 'UT', name: 'Utah' },
  { code: 'VT', name: 'Vermont' },
  { code: 'VA', name: 'Virginia' },
  { code: 'WA', name: 'Washington' },
  { code: 'WV', name: 'West Virginia' },
  { code: 'WI', name: 'Wisconsin' },
  { code: 'WY', name: 'Wyoming' },
]

export const COUNTIES: Record<string, string[]> = {
  AL: ['Jefferson','Mobile','Madison','Montgomery','Shelby','Baldwin','Tuscaloosa','Lee','Calhoun','Etowah','Houston','Marshall','Morgan','DeKalb','Limestone'],
  AK: ['Anchorage','Fairbanks North Star','Matanuska-Susitna','Kenai Peninsula','Juneau','Bethel','Kodiak Island','Yukon-Koyukuk','Nome','Kusilvak'],
  AZ: ['Maricopa','Pima','Pinal','Yavapai','Mohave','Yuma','Coconino','Navajo','Apache','Graham','Santa Cruz','Gila','La Paz','Greenlee'],
  AR: ['Pulaski','Benton','Washington','Sebastian','Faulkner','Saline','Garland','Craighead','Mississippi','White','Lonoke','Union','Miller','Carroll'],
  CA: ['Los Angeles','San Diego','Orange','Riverside','San Bernardino','Santa Clara','Alameda','Sacramento','Contra Costa','Fresno','Kern','San Francisco','Ventura','San Mateo','San Joaquin','Stanislaus','Sonoma','Tulare','Solano','Monterey','Santa Barbara','Placer','San Luis Obispo','Marin','Shasta','El Dorado','Merced','Butte','Yolo','Napa'],
  CO: ['El Paso','Denver','Jefferson','Arapahoe','Adams','Larimer','Douglas','Boulder','Weld','Pueblo','Mesa','Broomfield','Garfield','Eagle','La Plata','Fremont','Delta','Montrose','Summit','Routt'],
  CT: ['Fairfield','Hartford','New Haven','Middlesex','Tolland','Windham','New London','Litchfield'],
  DE: ['New Castle','Sussex','Kent'],
  FL: ['Miami-Dade','Broward','Palm Beach','Hillsborough','Orange','Pinellas','Duval','Lee','Polk','Brevard','Volusia','Pasco','Seminole','Sarasota','Manatee','Collier','Marion','Osceola','Alachua','St. Lucie','Leon','Lake','Hernando','Escambia','Clay','Bay','Charlotte','St. Johns','Okaloosa','Flagler'],
  GA: ['Fulton','Gwinnett','Cobb','DeKalb','Cherokee','Clayton','Forsyth','Henry','Hall','Richmond','Chatham','Columbia','Carroll','Bibb','Newton','Coweta','Paulding','Houston','Muscogee','Lowndes','Fayette','Douglas','Walton','Rockdale','Dougherty'],
  HI: ['Honolulu','Hawaii','Maui','Kauai','Kalawao'],
  ID: ['Ada','Canyon','Kootenai','Twin Falls','Bannock','Bonner','Bonneville','Nez Perce','Cassia','Jefferson','Madison','Bingham','Blaine','Elmore','Payette'],
  IL: ['Cook','DuPage','Lake','Will','Kane','McHenry','Winnebago','Madison','St. Clair','Champaign','Sangamon','Peoria','McLean','Rock Island','Tazewell','Macon','Kankakee','Whiteside','LaSalle','DeKalb'],
  IN: ['Marion','Lake','Allen','Hamilton','St. Joseph','Tippecanoe','Elkhart','Johnson','Vanderburgh','Delaware','Monroe','Madison','Hendricks','Vigo','Howard','Clark','Floyd','Bartholomew','Porter','Boone'],
  IA: ['Polk','Linn','Scott','Johnson','Black Hawk','Woodbury','Story','Dallas','Pottawattamie','Dubuque','Marion','Warren','Marshall','Clinton','Des Moines','Cerro Gordo','Webster','Muscatine','Jasper','Henry'],
  KS: ['Johnson','Sedgwick','Shawnee','Wyandotte','Douglas','Riley','Leavenworth','Reno','Butler','Harvey','Saline','Crawford','Finney','Ellis','Montgomery'],
  KY: ['Jefferson','Fayette','Kenton','Boone','Warren','Campbell','Hardin','Madison','Daviess','McCracken','Laurel','Oldham','Christian','Franklin','Clark'],
  LA: ['East Baton Rouge','Jefferson','Orleans','St. Tammany','Caddo','Calcasieu','Lafayette','Rapides','Terrebonne','Ascension','St. Landry','Ouachita','Lafourche','Beauregard','Bossier'],
  ME: ['Cumberland','York','Penobscot','Kennebec','Androscoggin','Knox','Oxford','Somerset','Aroostook','Hancock','Sagadahoc','Lincoln','Waldo','Piscataquis','Franklin','Washington'],
  MD: ['Montgomery','Prince George\'s','Baltimore','Anne Arundel','Howard','Frederick','Baltimore City','Charles','Carroll','Harford','Washington','Calvert','St. Mary\'s','Wicomico','Cecil'],
  MA: ['Middlesex','Worcester','Essex','Suffolk','Norfolk','Bristol','Plymouth','Hampden','Hampshire','Barnstable','Berkshire','Franklin','Dukes','Nantucket'],
  MI: ['Wayne','Oakland','Macomb','Kent','Genesee','Washtenaw','Ingham','Kalamazoo','Ottawa','Saginaw','Jackson','Livingston','Muskegon','St. Clair','Monroe','Bay','Berrien','Lapeer','Calhoun','Allegan'],
  MN: ['Hennepin','Ramsey','Dakota','Anoka','Washington','Scott','Sherburne','Wright','Olmsted','St. Louis','Stearns','Rice','Carver','Blue Earth','Crow Wing'],
  MS: ['Hinds','Harrison','DeSoto','Madison','Rankin','Forrest','Jackson','Lee','Lamar','Lowndes','Warren','George','Jones','Pike','Marshall'],
  MO: ['St. Louis','Jackson','St. Charles','Greene','Jefferson','Clay','Cass','Boone','St. Louis City','Franklin','Christian','Jasper','St. Francois','Cole','Newton'],
  MT: ['Yellowstone','Cascade','Missoula','Gallatin','Lake','Flathead','Ravalli','Hill','Lewis and Clark','Silver Bow','Rosebud','Carbon','Toole','Richland','Roosevelt'],
  NE: ['Douglas','Lancaster','Sarpy','Hall','Buffalo','Dodge','Platte','Madison','Lincoln','Dawson','Scotts Bluff','Cass','York','Adams','Gage'],
  NV: ['Clark','Washoe','Carson City','Elko','Douglas','Lyon','Churchill','Nye','Humboldt','Lander','White Pine','Storey','Eureka','Esmeralda','Mineral'],
  NH: ['Hillsborough','Rockingham','Merrimack','Strafford','Cheshire','Carroll','Grafton','Belknap','Sullivan','Coos'],
  NJ: ['Bergen','Middlesex','Essex','Hudson','Monmouth','Union','Ocean','Morris','Passaic','Camden','Burlington','Mercer','Atlantic','Somerset','Gloucester'],
  NM: ['Bernalillo','Dona Ana','Santa Fe','Sandoval','San Juan','Chavez','Otero','Rio Arriba','Lea','Eddy','Grant','Luna','Sierra','Valencia','Taos'],
  NY: ['Kings','Queens','New York','Suffolk','Bronx','Nassau','Westchester','Erie','Monroe','Richmond','Onondaga','Orange','Rockland','Albany','Dutchess','Saratoga','Niagara','Oneida','Broome','Schenectady'],
  NC: ['Mecklenburg','Wake','Guilford','Forsyth','Cumberland','Durham','Buncombe','Union','Cabarrus','Onslow','Gaston','New Hanover','Johnston','Alamance','Pitt','Randolph','Rowan','Catawba','Iredell','Lee'],
  ND: ['Cass','Burleigh','Grand Forks','Ward','Morton','Williams','Stark','Ramsey','Traill','McLean','Richland','Stutsman','Mountrail','Barnes','Pierce'],
  OH: ['Franklin','Cuyahoga','Hamilton','Summit','Montgomery','Lucas','Butler','Stark','Lorain','Warren','Lake','Mahoning','Medina','Greene','Clermont','Delaware','Clark','Licking','Allen','Fairfield'],
  OK: ['Oklahoma','Tulsa','Cleveland','Canadian','Comanche','Wagoner','Rogers','Creek','Muskogee','Osage','Payne','Pottawatomie','Garfield','Washington','Pittsburg'],
  OR: ['Multnomah','Washington','Clackamas','Lane','Marion','Jackson','Deschutes','Linn','Douglas','Yamhill','Benton','Josephine','Columbia','Klamath','Umatilla'],
  PA: ['Philadelphia','Allegheny','Montgomery','Bucks','Delaware','Chester','Lancaster','York','Luzerne','Berks','Westmoreland','Northampton','Erie','Lehigh','Cumberland','Dauphin','Centre','Monroe','Washington','Lackawanna'],
  RI: ['Providence','Kent','Washington','Newport','Bristol'],
  SC: ['Greenville','Richland','Charleston','Horry','Spartanburg','Anderson','Lexington','Beaufort','Dorchester','Berkeley','York','Pickens','Aiken','Florence','Cherokee'],
  SD: ['Minnehaha','Pennington','Lincoln','Brown','Codington','Brookings','Meade','Hamlin','Lawrence','Hughes','Butte','Davison','Rapid City area','Yankton','Clay'],
  TN: ['Shelby','Davidson','Knox','Hamilton','Williamson','Rutherford','Montgomery','Sumner','Blount','Madison','Sullivan','Wilson','Maury','Sevier','Robertson'],
  TX: ['Harris','Dallas','Tarrant','Bexar','Travis','Collin','Hidalgo','El Paso','Denton','Fort Bend','Montgomery','Williamson','Cameron','Nueces','Bell','Galveston','Lubbock','Jefferson','Webb','Smith','Hays','Ellis','Johnson','McLennan','Brazoria'],
  UT: ['Salt Lake','Utah','Davis','Weber','Washington','Cache','Iron','Tooele','Box Elder','Sanpete','Sevier','Millard','Kane','Duchesne','Carbon'],
  VT: ['Chittenden','Rutland','Washington','Windsor','Franklin','Addison','Orange','Lamoille','Bennington','Orleans','Caledonia','Grand Isle','Essex','Windham'],
  VA: ['Fairfax','Prince William','Loudoun','Chesterfield','Arlington','Henrico','Virginia Beach','Chesapeake','Newport News','Norfolk','Richmond City','Roanoke','Hampton','Alexandria','Suffolk','Spotsylvania','Stafford','Frederick','Augusta','Montgomery'],
  WA: ['King','Pierce','Snohomish','Spokane','Clark','Thurston','Kitsap','Whatcom','Benton','Skagit','Yakima','Cowlitz','Grant','Franklin','Grays Harbor'],
  WV: ['Kanawha','Cabell','Wood','Berkeley','Monongalia','Raleigh','Putnam','Mercer','Harrison','Greenbrier','Marshall','Wayne','Mineral','Marion','Lincoln'],
  WI: ['Milwaukee','Dane','Waukesha','Brown','Racine','Outagamie','Winnebago','Rock','Kenosha','Marathon','Washington','La Crosse','Ozaukee','Sheboygan','Polk'],
  WY: ['Laramie','Natrona','Campbell','Sweetwater','Fremont','Albany','Sheridan','Uinta','Lincoln','Park','Teton','Goshen','Platte','Carbon','Converse'],
}

export const CITIES: Record<string, string[]> = {
  // Alabama
  Jefferson: ['Birmingham','Hoover','Vestavia Hills','Bessemer','Homewood','Mountain Brook','Trussville','Alabaster'],
  Mobile: ['Mobile','Prichard','Saraland','Chickasaw','Satsuma','Tillmans Corner'],
  Madison: ['Huntsville','Madison','Decatur','Harvest','Triana'],
  Montgomery: ['Montgomery','Pike Road','Millbrook','Wetumpka','Prattville'],
  // Alaska
  Anchorage: ['Anchorage','Eagle River','Chugiak','Girdwood'],
  'Fairbanks North Star': ['Fairbanks','North Pole','College','Ester'],
  // Arizona
  Maricopa: ['Phoenix','Mesa','Chandler','Scottsdale','Glendale','Gilbert','Tempe','Peoria','Surprise','Avondale','Goodyear','Buckeye','Tolleson','El Mirage'],
  Pima: ['Tucson','Marana','Oro Valley','Sahuarita','South Tucson'],
  Pinal: ['Casa Grande','Maricopa','Apache Junction','Coolidge','Florence','Eloy'],
  Yavapai: ['Prescott','Prescott Valley','Cottonwood','Sedona','Camp Verde','Chino Valley'],
  Mohave: ['Kingman','Lake Havasu City','Bullhead City','Fort Mohave'],
  Yuma: ['Yuma','Somerton','San Luis','Wellton'],
  // Arkansas
  Pulaski: ['Little Rock','North Little Rock','Maumelle','Jacksonville','Sherwood','Bryant'],
  Benton: ['Bentonville','Rogers','Springdale','Bella Vista','Fayetteville','Siloam Springs'],
  Washington: ['Fayetteville','Springdale','Farmington','Prairie Grove','Elkins'],
  // California
  'Los Angeles': ['Los Angeles','Long Beach','Glendale','Santa Clarita','Lancaster','Pomona','Torrance','Pasadena','El Monte','Downey','West Covina','Norwalk','Burbank','Inglewood','Compton','Carson','Santa Monica','Hawthorne','Alhambra','Whittier'],
  'San Diego': ['San Diego','Chula Vista','Oceanside','Escondido','Carlsbad','El Cajon','Vista','San Marcos','Santee','Encinitas','National City','La Mesa','Poway','Lemon Grove'],
  Orange: ['Anaheim','Santa Ana','Irvine','Huntington Beach','Garden Grove','Fullerton','Orange','Corona del Mar','Newport Beach','Costa Mesa','Mission Viejo','Westminster'],
  Riverside: ['Riverside','Moreno Valley','Corona','Temecula','Murrieta','Menifee','Hemet','Perris','Indio','Palm Springs','Palm Desert'],
  'San Bernardino': ['San Bernardino','Fontana','Rancho Cucamonga','Ontario','Victorville','Rialto','Hesperia','Chino','Upland','Chino Hills','Apple Valley','Redlands'],
  'Santa Clara': ['San Jose','Sunnyvale','Santa Clara','Mountain View','Cupertino','Milpitas','Palo Alto','Gilroy','Campbell','Los Gatos'],
  Alameda: ['Oakland','Fremont','Hayward','Berkeley','San Leandro','Livermore','Pleasanton','Union City','Newark','Dublin'],
  Sacramento: ['Sacramento','Elk Grove','Roseville','Folsom','Citrus Heights','Rancho Cordova','Davis','West Sacramento','Woodland'],
  // Colorado
  'El Paso': ['Colorado Springs','Fountain','Manitou Springs','Falcon','Black Forest','Security-Widefield'],
  Denver: ['Denver','Englewood','Aurora','Lakewood','Thornton','Westminster','Arvada','Commerce City'],
  Jefferson: ['Lakewood','Arvada','Westminster','Golden','Wheat Ridge','Littleton','Edgewater'],
  Arapahoe: ['Aurora','Englewood','Littleton','Centennial','Greenwood Village','Cherry Hills Village'],
  Adams: ['Thornton','Commerce City','Westminster','Brighton','Northglenn','Federal Heights'],
  Larimer: ['Fort Collins','Loveland','Berthoud','Estes Park','Wellington'],
  Douglas: ['Castle Rock','Parker','Lone Tree','Highlands Ranch','Roxborough Park'],
  Boulder: ['Boulder','Longmont','Lafayette','Louisville','Erie','Broomfield'],
  // Connecticut
  Fairfield: ['Bridgeport','Stamford','Norwalk','Danbury','Greenwich','Westport','Fairfield','Trumbull','Shelton'],
  Hartford: ['Hartford','New Britain','Bristol','Meriden','West Hartford','Manchester','Enfield','Southington'],
  'New Haven': ['New Haven','Waterbury','Milford','West Haven','Hamden','Meriden','Derby'],
  // Delaware
  'New Castle': ['Wilmington','Newark','Bear','Middletown','Glasgow','Brookside','Pike Creek'],
  Sussex: ['Georgetown','Seaford','Lewes','Milford','Ocean View','Rehoboth Beach'],
  Kent: ['Dover','Milford','Smyrna','Harrington','Camden'],
  // Florida
  'Miami-Dade': ['Miami','Hialeah','Miami Gardens','Miami Beach','Homestead','North Miami','Coral Gables','Doral','Aventura','Kendall','Pembroke Pines'],
  Broward: ['Fort Lauderdale','Hollywood','Pembroke Pines','Miramar','Coral Springs','Plantation','Sunrise','Pompano Beach','Davie','Weston','Deerfield Beach'],
  'Palm Beach': ['West Palm Beach','Boca Raton','Boynton Beach','Delray Beach','Jupiter','Palm Beach Gardens','Wellington','Lake Worth','Greenacres'],
  Hillsborough: ['Tampa','Brandon','Riverview','Plant City','Temple Terrace','Town \'n\' Country','Westchase'],
  Orange: ['Orlando','Winter Garden','Apopka','Ocoee','Kissimmee','Sanford','Maitland','Altamonte Springs'],
  Pinellas: ['St. Petersburg','Clearwater','Largo','Dunedin','Tarpon Springs','Safety Harbor','Seminole'],
  Duval: ['Jacksonville','Jacksonville Beach','Neptune Beach','Atlantic Beach','Baldwin'],
  Lee: ['Fort Myers','Cape Coral','Bonita Springs','Estero','Lehigh Acres','Marco Island'],
  Polk: ['Lakeland','Winter Haven','Haines City','Bartow','Lake Wales','Auburndale'],
  // Georgia
  Fulton: ['Atlanta','Sandy Springs','Roswell','Johns Creek','Alpharetta','Milton','East Point','College Park'],
  Gwinnett: ['Lawrenceville','Duluth','Norcross','Snellville','Lilburn','Buford','Dacula','Suwanee'],
  Cobb: ['Marietta','Smyrna','Kennesaw','Acworth','Powder Springs','Austell'],
  DeKalb: ['Decatur','Dunwoody','Chamblee','Stone Mountain','Tucker','Brookhaven','Doraville'],
  Cherokee: ['Canton','Ball Ground','Holly Springs','Woodstock','Waleska'],
  Forsyth: ['Cumming','Suwanee','Johns Creek','Alpharetta'],
  // Hawaii
  Honolulu: ['Honolulu','Pearl City','Hilo','Kailua','Kaneohe','Waipahu','Mililani','Ewa Beach'],
  Hawaii: ['Hilo','Kailua-Kona','Waimea','Pahoa','Captain Cook'],
  Maui: ['Kahului','Wailuku','Kihei','Lahaina','Makawao','Kula'],
  // Idaho
  Ada: ['Boise','Meridian','Eagle','Kuna','Garden City','Star'],
  Canyon: ['Nampa','Caldwell','Middleton','Notus','Parma','Wilder'],
  Kootenai: ['Coeur d\'Alene','Post Falls','Hayden','Rathdrum','Spirit Lake'],
  // Illinois
  Cook: ['Chicago','Evanston','Skokie','Oak Park','Cicero','Berwyn','Arlington Heights','Naperville','Joliet','Waukegan','Des Plaines','Schaumburg','Elgin'],
  DuPage: ['Aurora','Naperville','Bolingbrook','Wheaton','Downers Grove','Elmhurst','Villa Park','Lombard'],
  Lake: ['Waukegan','North Chicago','Gurnee','Vernon Hills','Buffalo Grove','Mundelein','Lake Forest'],
  Will: ['Joliet','Romeoville','Bolingbrook','Plainfield','New Lenox','Lockport','Crest Hill'],
  // Indiana
  Marion: ['Indianapolis','Lawrence','Beech Grove','Speedway','Southport'],
  Lake: ['Gary','Hammond','Merrillville','Munster','Highland','Crown Point','Valparaiso'],
  Allen: ['Fort Wayne','New Haven','Woodburn','Leo-Cedarville','Huntertown'],
  Hamilton: ['Fishers','Carmel','Noblesville','Westfield','Cicero','Sheridan'],
  // Iowa
  Polk: ['Des Moines','Ankeny','West Des Moines','Urbandale','Johnston','Clive','Pleasant Hill'],
  Linn: ['Cedar Rapids','Marion','Hiawatha','Robins','Mount Vernon','Fairfax'],
  Scott: ['Davenport','Bettendorf','Eldridge','LeClaire','Buffalo'],
  // Kansas
  Johnson: ['Overland Park','Olathe','Lenexa','Shawnee','Leawood','Merriam','Prairie Village','Mission'],
  Sedgwick: ['Wichita','Derby','Haysville','Andover','Valley Center','Cheney'],
  Shawnee: ['Topeka','Auburn','Silver Lake','Rossville','Willard'],
  // Kentucky
  Jefferson: ['Louisville','Jeffersontown','Shively','St. Matthews','Middletown','Lyndon'],
  Fayette: ['Lexington','Nicholasville','Versailles','Georgetown','Winchester'],
  Kenton: ['Covington','Newport','Florence','Edgewood','Erlanger','Independence'],
  // Louisiana
  'East Baton Rouge': ['Baton Rouge','Zachary','Baker','Central','Denham Springs'],
  Jefferson: ['Metairie','Kenner','Gretna','Westwood','Marrero','Harvey','Terrytown'],
  Orleans: ['New Orleans'],
  'St. Tammany': ['Slidell','Covington','Mandeville','Bogalusa','Pearl River','Abita Springs'],
  // Maine
  Cumberland: ['Portland','South Portland','Westbrook','Gorham','Scarborough','Cape Elizabeth','Falmouth'],
  York: ['Saco','Biddeford','Sanford','Kennebunk','York','Wells','Kittery','South Berwick'],
  Penobscot: ['Bangor','Brewer','Old Town','Orono','Lincoln','Hampden'],
  // Maryland
  Montgomery: ['Rockville','Gaithersburg','Silver Spring','Bethesda','Germantown','Wheaton','Aspen Hill'],
  'Prince George\'s': ['Bowie','Laurel','College Park','Greenbelt','Hyattsville','Largo','Landover'],
  Baltimore: ['Towson','Dundalk','Parkville','Catonsville','Essex','Middle River','Rosedale'],
  'Anne Arundel': ['Annapolis','Glen Burnie','Laurel','Bowie','Odenton','Severn','Severna Park'],
  // Massachusetts
  Middlesex: ['Cambridge','Lowell','Newton','Somerville','Quincy','Waltham','Framingham','Malden','Medford','Woburn','Watertown'],
  Worcester: ['Worcester','Springfield','Fitchburg','Gardner','Leominster','Shrewsbury','Milford'],
  Essex: ['Salem','Lynn','Haverhill','Methuen','Lawrence','Peabody','Beverly','Gloucester'],
  Suffolk: ['Boston','Chelsea','Revere','Winthrop'],
  // Michigan
  Wayne: ['Detroit','Dearborn','Westland','Livonia','Warren','Lincoln Park','Dearborn Heights','Taylor'],
  Oakland: ['Troy','Southfield','Pontiac','Royal Oak','Farmington Hills','Auburn Hills','Rochester Hills','Sterling Heights'],
  Macomb: ['Sterling Heights','Warren','Clinton Township','St. Clair Shores','Roseville','Utica'],
  Kent: ['Grand Rapids','Wyoming','Kentwood','Walker','Grandville','East Grand Rapids'],
  // Minnesota
  Hennepin: ['Minneapolis','Brooklyn Park','Plymouth','Bloomington','Eden Prairie','Minnetonka','Edina','St. Louis Park','Burnsville'],
  Ramsey: ['St. Paul','Roseville','Maplewood','Shoreview','New Brighton','Arden Hills'],
  Dakota: ['Burnsville','Eagan','Apple Valley','Lakeville','Inver Grove Heights','Farmington'],
  Anoka: ['Coon Rapids','Blaine','Anoka','Brooklyn Park','Fridley','Spring Lake Park'],
  // Mississippi
  Hinds: ['Jackson','Clinton','Byram','Ridgeland','Flowood','Raymond'],
  Harrison: ['Gulfport','Biloxi','D\'Iberville','Long Beach','Pass Christian','Ocean Springs'],
  DeSoto: ['Southaven','Horn Lake','Hernando','Olive Branch','Walls','Walls'],
  // Missouri
  'St. Louis': ['Chesterfield','Florissant','Kirkwood','St. Peters','Clayton','Ballwin','St. Louis County'],
  Jackson: ['Kansas City','Independence','Lee\'s Summit','Blue Springs','Raytown','Grandview'],
  'St. Charles': ['St. Charles','O\'Fallon','St. Peters','Wentzville','Lake St. Louis','Cottleville'],
  Greene: ['Springfield','Republic','Nixa','Battlefield','Willard','Ozark'],
  // Montana
  Yellowstone: ['Billings','Lockwood','Laurel','Broadview','Columbus'],
  Cascade: ['Great Falls','Black Eagle','Belt','Cascade','Simms'],
  Missoula: ['Missoula','Lolo','Frenchtown','Clinton','Seeley Lake'],
  Gallatin: ['Bozeman','Belgrade','Manhattan','Three Forks','West Yellowstone'],
  // Nebraska
  Douglas: ['Omaha','Bellevue','Papillion','La Vista','Ralston','Valley'],
  Lancaster: ['Lincoln','Waverly','Hickman','Raymond','Emerald'],
  Sarpy: ['Bellevue','Papillion','La Vista','Gretna','Springfield'],
  // Nevada
  Clark: ['Las Vegas','Henderson','North Las Vegas','Enterprise','Sunrise Manor','Spring Valley','Paradise','Summerlin'],
  Washoe: ['Reno','Sparks','Sun Valley','Spanish Springs','Cold Springs'],
  'Carson City': ['Carson City'],
  Elko: ['Elko','Spring Creek','Carlin','Wells','West Wendover'],
  // New Hampshire
  Hillsborough: ['Manchester','Nashua','Milford','Merrimack','Bedford','Londonderry','Hudson','Amherst'],
  Rockingham: ['Derry','Portsmouth','Salem','Exeter','Hampton','Windham','Plaistow','Auburn'],
  // New Jersey
  Bergen: ['Hackensack','Paramus','Fort Lee','Englewood','Teaneck','Fair Lawn','Garfield','Clifton'],
  Middlesex: ['New Brunswick','Edison','Woodbridge','Piscataway','East Brunswick','Old Bridge','Sayreville'],
  Essex: ['Newark','Irvington','East Orange','Orange','Livingston','Bloomfield','Montclair','Nutley'],
  Hudson: ['Jersey City','Bayonne','Union City','West New York','Hoboken','Kearny','North Bergen'],
  // New Mexico
  Bernalillo: ['Albuquerque','Rio Rancho','Tijeras','Los Ranchos','South Valley','Corrales'],
  'Dona Ana': ['Las Cruces','Sunland Park','Anthony','Chaparral','Hatch','Mesilla'],
  'Santa Fe': ['Santa Fe','Española','Pojoaque','El Rancho','Chimayó'],
  // New York
  Kings: ['Brooklyn'],
  Queens: ['Flushing','Jamaica','Astoria','Jackson Heights','Corona','Forest Hills','Ridgewood'],
  'New York': ['Manhattan'],
  Suffolk: ['Islip','Brookhaven','Babylon','Huntington','Smithtown','Southampton','East Hampton'],
  Bronx: ['The Bronx'],
  Nassau: ['Hempstead','Long Beach','Glen Cove','Great Neck','Mineola','Garden City','Freeport'],
  Westchester: ['Yonkers','New Rochelle','Mount Vernon','White Plains','Greenburgh','Peekskill','Rye'],
  Erie: ['Buffalo','Cheektowaga','Tonawanda','Amherst','Niagara Falls','Lackawanna','Lancaster'],
  Monroe: ['Rochester','Greece','Irondequoit','Penfield','Webster','Brighton','Gates'],
  // North Carolina
  Mecklenburg: ['Charlotte','Pineville','Matthews','Mint Hill','Huntersville','Cornelius','Davidson','Mooresville'],
  Wake: ['Raleigh','Cary','Apex','Holly Springs','Fuquay-Varina','Morrisville','Wake Forest','Garner'],
  Guilford: ['Greensboro','High Point','Jamestown','Whitsett','Gibsonville'],
  Forsyth: ['Winston-Salem','Kernersville','Lewisville','Clemmons','Rural Hall'],
  Cumberland: ['Fayetteville','Spring Lake','Hope Mills','Eastover','Stedman'],
  Durham: ['Durham','Bethel','Bahama'],
  Buncombe: ['Asheville','Woodfin','Weaverville','Swannanoa','Black Mountain','Biltmore Forest'],
  Union: ['Monroe','Waxhaw','Indian Trail','Matthews','Stallings','Marvin','Wesley Chapel'],
  // North Dakota
  Cass: ['Fargo','West Fargo','Moorhead','Horace','Casselton','Kindred'],
  Burleigh: ['Bismarck','Lincoln','Wilton','Menoken','Regan'],
  'Grand Forks': ['Grand Forks','East Grand Forks','Emerado','Larimore','Thompson'],
  // Ohio
  Franklin: ['Columbus','Dublin','Westerville','Hilliard','Gahanna','Grove City','Reynoldsburg','Upper Arlington','Whitehall','Canal Winchester'],
  Cuyahoga: ['Cleveland','Cleveland Heights','Lakewood','Parma','Euclid','Strongsville','North Olmsted','Middleburg Heights'],
  Hamilton: ['Cincinnati','Norwood','Forest Park','Blue Ash','Fairfield','Mason','Loveland'],
  Summit: ['Akron','Cuyahoga Falls','Stow','Tallmadge','Barberton','Hudson','Twinsburg'],
  // Oklahoma
  Oklahoma: ['Oklahoma City','Edmond','Midwest City','Moore','Norman','Del City','Yukon','Mustang'],
  Tulsa: ['Tulsa','Broken Arrow','Owasso','Jenks','Bixby','Sand Springs','Sapulpa'],
  Cleveland: ['Norman','Moore','Midwest City','Little Axe','Slaughterville'],
  // Oregon
  Multnomah: ['Portland','Gresham','Troutdale','Fairview','Wood Village','Maywood Park'],
  Washington: ['Beaverton','Hillsboro','Tigard','Lake Oswego','Tualatin','Sherwood','Newberg'],
  Clackamas: ['Lake Oswego','Milwaukie','Happy Valley','West Linn','Oregon City','Canby','Wilsonville'],
  Lane: ['Eugene','Springfield','Cottage Grove','Junction City','Florence','Creswell'],
  Marion: ['Salem','Keizer','Woodburn','Silverton','Stayton','Turner'],
  Jackson: ['Medford','Ashland','Jacksonville','Grants Pass','Central Point','Eagle Point'],
  Deschutes: ['Bend','Redmond','Sisters','La Pine','Sunriver'],
  // Pennsylvania
  Philadelphia: ['Philadelphia'],
  Allegheny: ['Pittsburgh','McKeesport','Bethel Park','Mount Lebanon','Monroeville','Plum','Penn Hills'],
  Montgomery: ['Norristown','King of Prussia','Lansdale','Pottstown','Horsham','Abington','Plymouth Meeting'],
  Bucks: ['Levittown','Bristol','Doylestown','Newtown','Warminster','Horsham','Langhorne'],
  Delaware: ['Chester','Upper Darby','Haverford','Marple','Springfield','Ridley','Radnor'],
  Chester: ['West Chester','Coatesville','Phoenixville','Downingtown','Malvern','Kennett Square'],
  Lancaster: ['Lancaster','Ephrata','Lititz','Manheim','Elizabethtown','Columbia','Mountville'],
  York: ['York','Hanover','Dallastown','Red Lion','Spring Grove','Dover'],
  // Rhode Island
  Providence: ['Providence','Cranston','Pawtucket','North Providence','Johnston','Lincoln','North Smithfield'],
  Kent: ['Warwick','West Warwick','Coventry','East Greenwich','West Greenwich'],
  Washington: ['South Kingstown','Narragansett','Westerly','Hopkinton','Charlestown','Richmond'],
  // South Carolina
  Greenville: ['Greenville','Greer','Mauldin','Simpsonville','Taylors','Fountain Inn','Travelers Rest'],
  Richland: ['Columbia','Forest Acres','Cayce','Blythewood','Chapin'],
  Charleston: ['Charleston','North Charleston','Mount Pleasant','Summerville','Goose Creek','James Island','Hanahan'],
  Horry: ['Myrtle Beach','Conway','North Myrtle Beach','Surfside Beach','Socastee','Little River'],
  Spartanburg: ['Spartanburg','Duncan','Greer','Boiling Springs','Inman','Gaffney','Cowpens'],
  // Tennessee
  Shelby: ['Memphis','Germantown','Collierville','Bartlett','Cordova','Millington','Arlington'],
  Davidson: ['Nashville','Brentwood','Franklin','Antioch','Nolensville'],
  Knox: ['Knoxville','Farragut','Powell','Halls','Corryton','Hardin Valley'],
  Hamilton: ['Chattanooga','East Ridge','Red Bank','Soddy-Daisy','Signal Mountain','Collegedale'],
  Williamson: ['Franklin','Brentwood','Spring Hill','Nolensville','Thompson\'s Station','Fairview'],
  Rutherford: ['Murfreesboro','Smyrna','LaVergne','Rockvale','Lascassas','Eagleville'],
  // Texas
  Harris: ['Houston','Pasadena','Baytown','Katy','Sugar Land','Missouri City','League City','Pearland','Spring','Humble','Conroe'],
  Dallas: ['Dallas','Irving','Garland','Plano','Mesquite','Carrollton','Richardson','Grand Prairie','Rowlett','Balch Springs'],
  Tarrant: ['Fort Worth','Arlington','Grand Prairie','Mansfield','North Richland Hills','Euless','Bedford','Hurst','Keller','Grapevine','Southlake','Colleyville'],
  Bexar: ['San Antonio','Leon Valley','Converse','Universal City','Live Oak','Schertz','Helotes','Kirby'],
  Travis: ['Austin','Round Rock','Cedar Park','Georgetown','Pflugerville','Manor','Lakeway','Bee Cave'],
  Collin: ['Plano','McKinney','Frisco','Allen','Wylie','Murphy','Sachse','Prosper','Celina'],
  Hidalgo: ['McAllen','Edinburg','Mission','Pharr','Weslaco','Harlingen','Mercedes','Donna'],
  'El Paso': ['El Paso','Socorro','Anthony','Canutillo','Horizon City','San Elizario'],
  Denton: ['Denton','Lewisville','Carrollton','Flower Mound','Frisco','Little Elm','The Colony','Corinth','Argyle'],
  'Fort Bend': ['Sugar Land','Missouri City','Pearland','Richmond','Rosenberg','Stafford','Katy','Fulshear'],
  Williamson: ['Round Rock','Georgetown','Cedar Park','Pflugerville','Taylor','Hutto','Leander','Liberty Hill'],
  // Utah
  'Salt Lake': ['Salt Lake City','West Valley City','West Jordan','Sandy','Millcreek','South Jordan','Murray','Taylorsville','Midvale','Draper','Cottonwood Heights'],
  Utah: ['Provo','Orem','Lehi','American Fork','Spanish Fork','Springville','Payson','Saratoga Springs'],
  Davis: ['Layton','Bountiful','Kaysville','Clearfield','Clinton','Syracuse','Centerville','Farmington'],
  Weber: ['Ogden','Roy','South Ogden','Riverdale','Washington Terrace','Layton','Harrisville'],
  Washington: ['St. George','Washington','Hurricane','Ivins','Santa Clara','La Verkin'],
  // Vermont
  Chittenden: ['Burlington','South Burlington','Williston','Shelburne','Essex','Colchester','Winooski','Milton'],
  Rutland: ['Rutland','Castleton','Poultney','Pittsford','Killington','Proctor'],
  // Virginia
  Fairfax: ['Fairfax','Alexandria','Reston','Herndon','McLean','Vienna','Annandale','Springfield','Centreville','Chantilly'],
  'Prince William': ['Manassas','Woodbridge','Dale City','Gainesville','Lake Ridge','Dumfries','Bristow'],
  Loudoun: ['Leesburg','Ashburn','Sterling','Dulles','Broadlands','Lansdowne','Purcellville'],
  Chesterfield: ['Chesterfield','Midlothian','Chester','Bon Air','Colonial Heights'],
  Arlington: ['Arlington','Ballston','Clarendon','Rosslyn','Pentagon City'],
  Henrico: ['Richmond','Glen Allen','Henrico','Sandston','Short Pump','Lakeside'],
  // Washington state
  King: ['Seattle','Bellevue','Kent','Renton','Federal Way','Kirkland','Redmond','Sammamish','Shoreline','Burien','Auburn','Bothell'],
  Pierce: ['Tacoma','Lakewood','Federal Way','Puyallup','Renton','Bonney Lake','Gig Harbor','Sumner','Milton','Edgewood'],
  Snohomish: ['Everett','Marysville','Lynnwood','Edmonds','Mountlake Terrace','Bothell','Shoreline','Mukilteo','Mill Creek'],
  Spokane: ['Spokane','Spokane Valley','Cheney','Medical Lake','Liberty Lake','Airway Heights'],
  Clark: ['Vancouver','Camas','Washougal','Battle Ground','Ridgefield','La Center'],
  // West Virginia
  Kanawha: ['Charleston','South Charleston','St. Albans','Dunbar','Nitro','Hurricane','Cross Lanes'],
  Cabell: ['Huntington','Barboursville','Milton','Kenova','Ceredo'],
  Wood: ['Parkersburg','Vienna','Williamstown','Belpre','Marietta'],
  Berkeley: ['Martinsburg','Inwood','Hedgesville','Bunker Hill','Falling Waters'],
  Monongalia: ['Morgantown','Westover','Star City','Granville','Cheat Lake'],
  // Wisconsin
  Milwaukee: ['Milwaukee','Wauwatosa','West Allis','Greenfield','Racine','Oak Creek','South Milwaukee','Greendale'],
  Dane: ['Madison','Sun Prairie','Middleton','Fitchburg','Monona','Verona','Stoughton','DeForest'],
  Waukesha: ['Waukesha','Brookfield','New Berlin','Muskego','Oconomowoc','Pewaukee','Sussex','Menomonee Falls'],
  Brown: ['Green Bay','De Pere','Allouez','Ashwaubenon','Bellevue','Howard','Pulaski'],
  // Wyoming
  Laramie: ['Cheyenne','Burns','Pine Bluffs','Albin','Hillsdale'],
  Natrona: ['Casper','Mills','Evansville','Bar Nunn','Midwest'],
  Campbell: ['Gillette','Wright','Recluse'],
  Sweetwater: ['Rock Springs','Green River','Reliance','Point of Rocks'],
  Fremont: ['Lander','Riverton','Dubois','Hudson','Shoshoni'],
  Teton: ['Jackson','Wilson','Teton Village','Alta'],
}
